### ISSUE TITLE
Add specialised abs2 function

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#100]
```jl
abs2(x::Interval) = x^2
```

**Comment by dpsanders** [comment]
Generic fallback is `x*x`

**Comment by eeshan9815** [comment]
@dpsanders As per my understanding, absolute value of an interval is defined to be between the mignitude and magnitude of the interval. How is the squared absolute value defined?

**Comment by dpsanders** [comment]
Hmm. I thought I had given the definition in the the first comment of this issue, but now I'm not so sure.

In general, for a unary function $f$ (which is the case with `abs2`, i.e. a function that takes a single argument), we want to define the action of $f$ on an interval $X$ to be the smallest interval that contains the range $\{f(x): x \in X\}$. This should define how to calculate `abs2`. 

Yes, I believe that following that definition, my original idea was correct, since `abs2(x)` means `|x|^2`.
