### ISSUE TITLE
Define a name for Union{Interval, IntervalBox}

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#110]

**Comment by dpsanders** [comment]
Currently `AbstractInterval` is the union of `Interval` and `DecoratedInterval`, I believe.

An `IntervalBox` is maybe not actually an `Interval`?

Anyway, it's not really that important.

**Comment by Kolaru** [comment]
What about `Region` ? @gwater introduced it as parameter name and it sounds right and descriptive to me.  `IntervalRootFinding` uses the concept quite a lot so its usefulness is increasing (and I am eager to remove the ugly `IntervalLike` that I introduced in some places ^^).

**Comment by dpsanders** [comment]
I like Region!
