### ISSUE TITLE
New docs not visible

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#123]
The new docs don't seem to be being picked up:

https://juliaintervals.github.io/IntervalArithmetic.jl/latest/

**Comment by dpsanders** [comment]
Seems to be due to errors in doctests:

https://travis-ci.org/JuliaIntervals/IntervalArithmetic.jl/jobs/365375185

**Comment by lbenet** [comment]
It may take a bit longer...

**Comment by lbenet** [comment]
Ups...

**Comment by dpsanders** [comment]
Fixed by #124
