### ISSUE TITLE
Bug in a - x

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#130]
#125 introduced a bug in `a - x` for a constant `a`:

(EDITed the example):
```
julia> x = 1..2
[1, 2]

julia> 3.0 - x
[2, 1]
```
Note that the result is the wrong way round.

cc @lbenet

**Comment by dpsanders** [comment]
We certainly need to be testing this stuff!

**Comment by dpsanders** [comment]
Sorry this example is fine...

**Comment by lbenet** [comment]
Fixed by #131
