### ISSUE TITLE
Use FemtoCleaner to update to 0.7

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#163]

**Comment by lbenet** [comment]
I noticed that femtocleaner checked #162; is there a way to control that?

**Comment by dpsanders** [comment]
I'm not sure; the usage instructions are here:

https://discourse.julialang.org/t/femtocleaner-usage-howto/11762

**Comment by dpsanders** [comment]
Fixed by #201.
