### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#167]
We should tag a new minor version after #166 is merged, which will be the final one to support Julia 0.6!

cc @lbenet

**Comment by lbenet** [comment]
I fully agree. But this involves also some changes in ValidatedNumerics, so tests also pass there. I think the suggestion was to add a maximum version in ValidatedNumerics so things behave smoothly.

**Comment by lbenet** [comment]
And probably update `REQUIRE` in other packages as well (e.g., IntervalRootFinding).

**Comment by dpsanders** [comment]
I think we should remove all the explicit tests in ValidatedNumerics and just test that loading the individual packages works.

**Comment by dpsanders** [comment]
I believe we will need to add an upper bound for allowed versions of IntervalArithmetic in current and previous versions of IntervalRootFinding.

**Comment by lbenet** [comment]
The tests in ValidatedNumerics are so basic that they are not the issue. In any case it is probably a good idea to proceed as you propose.

**Comment by dpsanders** [comment]
I think we are ready to tag a new version?
Is there anything else that is urgent to go in? cc @lbenet @eeshan9815

**Comment by lbenet** [comment]
I fully agree to tag a new version!

Maybe we will need to tag patch versions in other packages before, setting upper limits in the requirements of  the packages that depend on `IntervalArithmetics` (as `ValidatedNumerics` or `IntervalRootFinding`).

**Comment by dpsanders** [comment]
OK great !

It's not necessary to tag versions just to fix the upper bound - that's done by a direct pr to metadata.

**Comment by eeshan9815** [comment]
Yes definitely! This will lead to a lot of PRs passing tests in IntervalRootFinding

**Comment by dpsanders** [comment]
Done.
