### ISSUE TITLE
Display 1-dimensional IntervalBox more clearly

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#171]
```
julia> X = IntervalBox(-∞..∞)
[-∞, ∞]

julia> X[1]
[-∞, ∞]
```
These two should be differentiated in the output.

**Comment by lbenet** [comment]
What about adding `{ ... }` to distinguish `IntervalBox`es from `Interval`s? So in your example above, we would get
```julia
julia> X = IntervalBox(-∞..∞)
{ [-∞, ∞] }
```

Another possibility is to include `×` at the end of `IntervalBox{1,T}`; it looks a bit weird, but the idea is to distinguish that.

**Comment by dpsanders** [comment]
I don't particularly like the `{`. I agree that the solitary `×` looks weird, but that's a good solution at least for now.
