### ISSUE TITLE
Accelerate pow

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#18]
Do rounding down and up separately, not as an interval.

**Comment by dpsanders** [comment]
I think this will require our own version of `power_by_squaring`, in order to be able to specify the rounding mode to use in the multiplications.

**Comment by dpsanders** [comment]
In this particular case, it's not clear that this will be faster than changing the rounding mode for large powers.

**Comment by OlivierHnt** [comment]
I believe this has been addressed in PR #593, although there is still some room for improvement when it comes to performance. But presumably we should open a new issue if this rises again.
