### ISSUE TITLE
Transition to Julia v0.7 and v1.0

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#193]
- [x] Change Travis and Appveyor to test on 0.7 and 1.0 (allowed failure).
- [x] Fix bugs listed below.
- [x] Once everything passes on 0.7 with no deprecation warnings, reenable full testing on 1.0 and nightly.
- [x] Fix more bugs if necessary (it shouldn't be...)
- [x] Make a release -- v1.0?

----

- [x] Incorrect conversion `Bool` -> `Interval`. https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/189

- [x] `atan2` -> `atan`.  https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/ 192

- [x] Failing bisection tests.  https://travis-ci.org/JuliaIntervals/IntervalArithmetic.jl/jobs/416496303

- [x] Others found along the way - see #194.

- [x] Use `SetRounding.jl`.

**Comment by lbenet** [comment]
Thanks for opening this!

The first point is addressed in #169 and #190 (probably #190 should be closed).

Regarding enabling testing for Julia 1.0, I think we should include it explicitly, allowing it to fail.

Aside from what you have included, other packages which depend on IntervalArithmetic should be tagged to use at most v0.14.0.

**Comment by dpsanders** [comment]
Just a heads up that I am most of the way through the Julia 0.7 deprecation warnings, just so that we don't duplicate work...

**Comment by lbenet** [comment]
Agreed :-)

**Comment by dpsanders** [comment]
#194 is ready to merge, which makes master work fully on Julia 1.0 (except for powers of complex intervals, which Julia itself broke).

**Comment by dpsanders** [comment]
0.15 has been tagged.
