### ISSUE TITLE
Use IOContext internally

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#197]
https://docs.julialang.org/en/latest/base/io-network/#Base.IOContext-Tuple%7BIO,Pair%7D

**Comment by dpsanders** [comment]
Example from Sebastian Pfitzner:

```jl
function show(io::IO, ::MyType)
  limited = get(io, :limit, false)
  limited ? print(io, "short") : print(io, "looooooooong")
end
```

**Comment by OlivierHnt** [comment]
@dpsanders

Could you elaborate on this? On master we use `get(io, :compact, false)` for the display. Is this what was meant?

**Comment by OlivierHnt** [comment]
Closing this as I believe it has been resolved on master.
