### ISSUE TITLE
FastRounding.jl's newest release broke v0.6 compatibility

### ISSUE THREAD

**Issue by schillic** [JuliaIntervals/IntervalArithmetic.jl#199]
(Sorry if this is the wrong place to report*.)
CC @JeffreySarnoff

On a fresh install, this package does not work anymore on Julia v0.6 due to a [new release of `FastRounding.jl`](https://github.com/JeffreySarnoff/FastRounding.jl/releases) today.

EDIT: Proposal: You could lock the old version in the `REQUIRE` file (see [here](https://docs.julialang.org/en/v0.6.4/manual/packages/#Requirements-Specification-1) for how to do that; for Julia v0.7 a [`Project.toml` file](https://docs.julialang.org/en/stable/stdlib/Pkg/#Glossary-1) can be used in parallel to the `REQUIRE` file where you can work with the newer releases).

Excerpt from a Travis CI build today:
```julia
ERROR: LoadError: syntax: "⊕" is not a unary operator
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] anonymous at ./<missing>:2
while loading /home/travis/.julia/v0.6/FastRounding/src/FastRounding.jl, in expression starting on line 5
ERROR: LoadError: Failed to precompile FastRounding to /home/travis/.julia/lib/v0.6/FastRounding.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /home/travis/.julia/v0.6/IntervalArithmetic/src/IntervalArithmetic.jl, in expression starting on line 9
ERROR: LoadError: LoadError: Failed to precompile IntervalArithmetic to /home/travis/.julia/lib/v0.6/IntervalArithmetic.ji.
```

*Side note: The Gitter link on the front page does not work.

**Comment by schillic** [comment]
Note that this problem only occurs on Julia v0.6.4. Any previous v0.6.x versions work fine because `FastRounding` is automatically downgraded to `v0.5.0`, which itself happens because any newer version requires a newer version of `ErrorfreeArithmetic`, which again requires Julia v0.6.4 :smiley:

**Comment by JeffreySarnoff** [comment]
hmmm ... asking Slack for Ideas [preferably for you :)]

**Comment by JeffreySarnoff** [comment]
The unicode infix ops introduced with v0.2.0 are here to stay.  Your message requests that running v0.6.4 opt out of using this new release.  A way to do that is ok iff there are no other effects.

**Comment by JeffreySarnoff** [comment]
Would updating ErrorfreeArithmetic to require Julia v0.7- solve this?

**Comment by schillic** [comment]
@JeffreySarnoff: I only CC'ed you to know about this.
My suggestion would be:
* for `FastRounding`: Modify `REQUIRE` to `julia 0.7` (you already did that - thanks). But this will not help with the existing release I think.
* for `IntervalArithmetic`: Modify `REQUIRE` from `FastRounding 0.0.4` to `FastRounding 0.0.4 0.2.0`. This will make sure that at most a release older than `0.2.0` is used (according to the documentation I linked about, the upper bound is exclusive).

**Comment by JeffreySarnoff** [comment]
David, you should not get on a train that prevents JuliaIntervals from
using whatever the current version of  FastRounding
 be.  Perhaps there is a way to limit the version selected for people  who
are using v0.6.4 only.  We should ask #PkgDev on slack (tag).

**Comment by schillic** [comment]
As far as I know, the `REQUIRE` file is only meant up to Julia v0.6. You can still continue using the most recent version with a `Project` file in newer versions. I might be wrong, though.

**Comment by JeffreySarnoff** [comment]
eventually -- not today, when v1 is no longer a release candidate

**Comment by dpsanders** [comment]
The latest release of FastRounding should not be available on 0.6, due to FastRounding's REQUIRE.

How did you install the packages?
What does `Pkg.status()` give? What if you do `Pkg.free("FastRounding")`?

**Comment by dpsanders** [comment]
Probably we should in any case upper bound FastRounding to the last working version. Which was that?

**Comment by schillic** [comment]
The `REQUIRE` in the release version still had `julia 0.6` in it ([link](https://github.com/JeffreySarnoff/FastRounding.jl/blob/v0.2.0/REQUIRE)).
Locally it works for me because I have Julia v0.6.2, but this is a coincidence. Our Travis build installs the latest version v0.6.4.

**Comment by JeffreySarnoff** [comment]
that is not available

**Comment by dpsanders** [comment]
@JeffreySarnoff Did you intend to still support Julia 0.6 in FastRounding.jl? I confirm that v0.2 does not work with Julia 0.6.4. If Julia 0.6 is still supported, then Travis should be testing on 0.6.

**Comment by dpsanders** [comment]
I am not sure what the best solution is here.

**Comment by lbenet** [comment]
A possibility, as @schillic mentioned, is to have an upper bound in the REQUIRE file of IntervalArithmetic.jl, something like `FastRounding 0.0.4 0.2.0`. In order for this to take effect for anyone using Julia 0.6.x, a new version of IntervalArithmetic.jl needs to be tagged.

**Comment by schillic** [comment]
Another hack is to have a new release of `FastRounding`, say `0.2.1`, which is identical to the old release `1.2.0`, and then have another release, say `0.2.2`, which is identical to the current `0.2.0` release apart from the updated `REQUIRE`.
Anyway, you know best what to do :+1:

**Comment by schillic** [comment]
The fix got merged and everything works again.
Thank you all for the quick help, I appreciate it!
