### ISSUE TITLE
Bug casting Inf to Interval

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#209]
```
julia> convert(Interval, ∞)
[∞, ∞]
```

**Comment by dpsanders** [comment]
Also
```
julia> Interval{Float64}(∞)
[∞, ∞]
```
This is a prohibited interval. We could either throw an error or return `Interval(prevfloat(Inf), Inf)`.

**Comment by lbenet** [comment]
I'm in favor of throwing an error here; in whatever interpretation of an Interval, it simply makes no sense.

In pass, note that `atomic` yields your last solution
```julia
julia> IntervalArithmetic.atomic(Interval{Float64}, ∞)
[1.79769e+308, ∞]
```
