### ISSUE TITLE
Bugs with tiny numbers

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#215]
```jl
julia> tiny = interval(0, floatmin())
[0, 2.22508e-308]

julia> huge = interval(floatmax(), Inf)
[1.79769e+308, ∞]

julia> tiny * tiny
[0, 0]

julia> huge * huge
[1.79769e+308, ∞]

julia> huge / tiny
[1.79769e+308, ∞]

julia> tiny / huge
[0, 0]
```

In particular, `tiny*tiny` and `tiny / huge` should not be exactly 0.

cc @JeffreySarnoff

**Comment by dpsanders** [comment]
This may be to do with corner cases in FastRounding.jl.

**Comment by dpsanders** [comment]
Using directed rounding via changing the rounding mode gives correct answers:
```jl
julia> setrounding(Interval, :slow)
:slow

julia> tiny * tiny
[0, 4.94066e-324]

julia> tiny / huge
[0, 4.94066e-324]
```

**Comment by JeffreySarnoff** [comment]
How do you get `2.25e-308 * 2.25e-308` not `0.0` with any rounding mode?
```
frexp(floatmin(Float64))
(0.5, -1021)
```
`floatmin(Float64) * floatmin(Float64) = ldexp(0.5 * 0.5, -1021 -1021) == ldexp(0.25, -2042)`

**Comment by dpsanders** [comment]
Ah, the problem is here:
```jl

julia> x = floatmin()
2.2250738585072014e-308

julia> two_prod(x, x)
(0.0, 0.0)
```
which is correct as far as it goes...

**Comment by JeffreySarnoff** [comment]
are these issues limited to denormals?

**Comment by dpsanders** [comment]
No, I think it's any numbers for which the low-order part of `two_prod` is 0, so `x <= 1e-151` approximately.

**Comment by JeffreySarnoff** [comment]
Is it only products?

**Comment by JeffreySarnoff** [comment]
This is the other side of my note earlier about how low order 0.0 usually are nonzero [although guessing whether the value >0.0 or <0.0 seems difficult]

**Comment by JeffreySarnoff** [comment]
Do you think we need to trap and special case products where an arg < ~1.0e-150?

**Comment by dpsanders** [comment]
It seems like special casing there is necessary, yes :/

I guess there will be the same problem with division for small and large numbers.

**Comment by JeffreySarnoff** [comment]
even at doubled-double precision (4 Float64 parts), we would not see all nonzero lesser parts

**Comment by JeffreySarnoff** [comment]
this is messy

**Comment by JeffreySarnoff** [comment]
Is this the logic you see for mul with tiny [is huge messed up also?]:
> @inline function mul_round(a::T, b::T, rounding::R)::T where {T<:SysFloat, R<:RoundingMode}
           hi, lo = two_prod(a, b)
           !iszero(hi) && return round_errorfree(hi, lo, rounding)
           (iszero(a) || iszero(b)) && return zero(T)
           rounding === RoundDown && return prevfloat(zero(T))
           rounding === RoundUp   && return nextfloat(zero(T))
           zero(T)
       end

**Comment by dpsanders** [comment]
Yes, that kind of thing, but with that definition I still get
```
julia> FastRounding.mul_round(0.0, nextfloat(0.0), RoundUp)
0.0
```

**Comment by dpsanders** [comment]
Sorry, my mistake, that should be 0 ...

**Comment by dpsanders** [comment]
But this shouldn't: 
```
julia> FastRounding.mul_round(nextfloat(0.0), nextfloat(0.0), RoundUp)
0.0
```

**Comment by dpsanders** [comment]
Ignore me, looks like I didn't succeed in redefining the function correctly; seems to be working.

**Comment by JeffreySarnoff** [comment]
natch

**Comment by JeffreySarnoff** [comment]
Because most cases are unexceptional, the usual extra cost is `!(iszero(hi) || isinf(hi))` and that is not nearly as costly as other approaches. So, if I do something similar with division, are `+` and `-` ok?

**Comment by dpsanders** [comment]
The following should give 0.0:
```
julia> x = nextfloat(0.0)
5.0e-324

julia> *(x, x, RoundDown)
-5.0e-324
```

**Comment by dpsanders** [comment]
Here's another class of problem:
```
julia> x = sqrt(2) * 1e-160
1.4142135623730952e-160

julia> *(x, x, RoundDown)
HELLO
2.0e-320

julia> *(x, x, RoundUp)
HELLO
2.0e-320
```
These should not give the same result. I'm really not sure what to do about these cases.

**Comment by JeffreySarnoff** [comment]
this fixes the first of those two issues
```julia
 function mul_round(a::T, b::T, rounding::RoundingMode) where {T<:Base.IEEEFloat}
                  hi, lo = two_prod(a, b)
                  if !(iszero(hi) || isinf(hi))
                      round_errorfree(hi, lo, rounding)
                  elseif iszero(hi)
                      if iszero(a) || iszero(b)
                          hi
                      elseif rounding === RoundDown
                          signbit(hi) ? prevfloat(zero(T)) : hi
                      elseif rounding === RoundUp
                          signbit(hi) ? hi : nextfloat(zero(T))
                      else
                          hi
                      end
                  else
                      if isinf(a) || isinf(b)
                          hi
                      elseif rounding === RoundDown
                          signbit(hi) ? hi : prevfloat(hi)
                      elseif rounding === RoundUp
                          signbit(hi) ? nextfloat(hi) : hi
                      elseif rounding === RoundToZero
                          signbit(hi) ? nextfloat(hi) : prevfloat(hi)
                      else
                          hi
                      end
                  end
end
```

**Comment by JeffreySarnoff** [comment]
I may have an approach to the second.  
```
julia> two_prod(0.25,0.25)
(0.0625, 0.0)
```
you want `mul_round(0.25, 0.25, RoundUp) == mul_round(0.25, 0.25, RoundDown)` right?
It's going to be about differentiating the exact results with lower part zero from the inexact ones.

**Comment by dpsanders** [comment]
Yes, exactly. Exact results must have the `RoundDown` and `RoundUp` equal. (I will use this in a future incarnation of IntervalArithmetic to check if endpoints should be included.)

**Comment by JeffreySarnoff** [comment]
I added the newer mul_round, and your sqrt.
Is it necessary to round the test squared-value up[down].  It looks as though the logic wouldwork using round to nearest, so the test would become `if hi*hi > a`, which would be yet faster, if legit.

**Comment by dpsanders** [comment]
Yes, I think that should work...

**Comment by JeffreySarnoff** [comment]
do you have a few test cases for division using different rounding modes?  if so -- let me see

**Comment by JeffreySarnoff** [comment]
the new mul_round:
```julia
@inline function mul_round(a::T, b::T, rounding::RoundingMode) where {T<:SysFloat}
    isexactprod(a, b) && return a*b

    hi, lo = two_prod(a, b)
    if !(iszero(hi) || isinf(hi))
        round_errorfree(hi, lo, rounding)
    else
        mul_round_specialvalues(a, b, hi, rounding)
    end
end
```

**Comment by matsueushi** [comment]
Is this issue still open?

I think Kashiwagi's algorithm of emulating directed rounding using twosum and twoprod (`-DKV_NOHWROUND` option in http://verifiedby.me/kv/rounding/index-e.html) can solve this.

The idea how to avoid errors caused by overflow and underflow is described in the [article]( http://verifiedby.me/kv/rounding/emu.pdf) (in Japanese, I cannot find English ver). You can find [his original C++ implementation](https://github.com/mskashi/kv/blob/2ec8bac6216d25b226c09e1740487837a4fc5fd5/test/test-nohwround.cc#L120) as a part of [kv](https://github.com/mskashi/kv).

The package https://github.com/matsueushi/RoundingEmulator.jl is my Julia implementation of his algorithm. It would be slower than Fastrounding.jl but gives proper rounded values for the inputs in the discussion above.

```julia
julia> using RoundingEmulator

julia> mul_up(floatmin(), floatmin())
5.0e-324

julia> mul_down(floatmin(), floatmin())
0.0

julia> x = nextfloat(0.0)
5.0e-324

julia> mul_up(x, x)
5.0e-324

julia> mul_down(x, x)
0.0

julia> x = sqrt(2) * 1e-160
1.4142135623730952e-160

julia> mul_up(x, x)
2.0005e-320

julia> mul_down(x, x)
2.0e-320
```

**Comment by dpsanders** [comment]
Hi, yes it's still open. Thanks, this looks great! I'll check this in detail when I have a moment.

**Comment by dpsanders** [comment]
@matsueushi Would you like to try adding this as another rounding option in `IntervalArithmetic.jl` and running the tests? That will be a pretty stringent test of whether your code is correct (except it won't test these important edge cases). I don't expect I'll have time to do this for a while.

cc also @krish8484

**Comment by matsueushi** [comment]
Sure, I'll give it a try.

**Comment by lucaferranti** [comment]
now master uses RoundingEmulator.jl by default, which fixes that
