### ISSUE TITLE
∞🔁🐞 : ==(DecoratedInterval, Interval) gives an infinite loop.

### ISSUE THREAD

**Issue by miguelraz** [JuliaIntervals/IntervalArithmetic.jl#219]
```
using IntervalArithmetic
DecoratedInterval(1,2) == Interval(1, 2)
```

Versioninfo()
``` [d1acc4aa] IntervalArithmetic v0.15.0+ [`~/.julia/dev/IntervalArithmetic`]```

```
julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (i686-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
  WORD_SIZE: 32
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

**Comment by dpsanders** [comment]
It doesn't really crash, just hangs. If you wait long enough, it should give a `StackOverflowError` I guess. Thanks for the bug report.

We just need to define `==` for a `DecoratedInterval` and an `Interval`. I guess it should always return `false`.

**Comment by lbenet** [comment]
> We just need to define `==` for a `DecoratedInterval` and an `Interval`. I guess it should always return `false`.

I agree that it is just a matter of defining `==` for `DecoratedInterval` and `Interval`; however, I am not sure if it should return always `false`, an error, or something more elaborated. As an example, any well-defined interval is equivalent to a trivial interval (`trv`), so for that comparison `true` seems to be a reasonable result. In that case, `Interval` should be "promoted" to a `DecoratedInterval` with `trv` decorqation. Another option is to throw a `MethodError` (or a `DomoainError`?) simply to make clear to the user that two `DecoratedInterval`s should be considered in the comparison.

**Comment by dpsanders** [comment]
Are there other comparisons of decorated and undecorated intervals in the new tests in ITF1788 @miguelraz ?

**Comment by miguelraz** [comment]
Yes, in the newest tests, there are more.

1. "minimal_less_dec_test", L262
```
    @test ≤(DecoratedInterval(∅, trv), nai()) == false # Breaks!
```
Can be addressed by defining a similar `false` fallback.

2.  "minimal_precedes_dec_test", L318-320, , 
```
@test precedes(nai(), DecoratedInterval(Interval(3.0, 4.0), def)) == false
```
Can define a similar method fallback.

3. "minimal_interior_dec_test", L381 and 5 others
```
@test ⪽(nai(), nai()) == false
@test ⪽(nai(), DecoratedInterval(Interval(0.0, 4.0), trv)) == false
```

Similar fallback

4. "minimal_strictly_less_dec_test", hangs infinitely in promote loop.
```
@test <(DecoratedInterval(∅, trv), nai()) == false
```

5. "minimal_strictly_precedes_dec_test", 15 test failures
```
@test strictprecedes(nai(), DecoratedInterval(Interval(3.0, 4.0), trv)) == false
```

6. "minimal_disjoint_dec_test", 3 failures.
```
@test isdisjoint(nai(), DecoratedInterval(Interval(3.0, 4.0), def)) == false
````

The only comparisons in the testsets that seem to exist between `DecoratedInterval`s and `Intervals` are with `[NaN,NaN] == nai()`.

**Comment by dpsanders** [comment]
Well if we were to go the route that you suggest @lbenet, we should use the conversion that already exists, rather `trv`:

```jl
julia> setformat(decorations=true)
6

julia> DecoratedInterval(1..2)
[1, 2]_com

julia> DecoratedInterval(1..∞)
[1, ∞]_dac
```
This comes from the standard IIRC.

**Comment by miguelraz** [comment]
I made a gist of the number, kind, and file for errors in the path to compliance.
They [are available in this gist](https://gist.github.com/miguelraz/ad0253f9068d0a7ca942745222e99dbb) though I will raise it as a roadmap issue in IntervalArithmetic.jl later.

I do think @lbenet 's generic fallback is needed at some point, but don't know how to approach the promotion mechanism yet.

**Comment by lbenet** [comment]
@dpsanders I fully agree.

The example was simply to show that there are ways of promoting `Interval`s to `DecoratedInterval`s which make sense. We can choose the "smallest" (say `trv`) or the highest (`com`) in the ordered sequence of decorations; I have no idea if one makes actually more sense than the other. 

Noting that
```julia
julia> DecoratedInterval(1..2, com) == DecoratedInterval(1..2, trv)
true
```
I guess either choice is actually fine.

Therefore, we should either define `==` for `DecoratedInterval`s and `Interval`s as
```
==(a::DecoratedInterval, b::Interval) = ==(promote(a, b)...)
```
which would require to add the promotion rule, or as
```
==(a::DecoratedInterval, b::Interval) = ==(a, convert(DecoratedInterval, b))
```
which would work now.

**Comment by dpsanders** [comment]
> julia> DecoratedInterval(1..2, com) == DecoratedInterval(1..2, trv)
> true

I think this is wrong... They should be equal only if the decorations are also the same.

**Comment by lbenet** [comment]
I'm not sure; i guess the standard should get us out of doubts :-)

**Comment by dpsanders** [comment]
I think the simplest thing for now is to throw an `ArgumentError` for `=` between a `DecoratedInterval` and an `Interval`.

**Comment by OlivierHnt** [comment]
On master

```Julia
julia> DecoratedInterval(1,2) == interval(1, 2)
false
```

since `==` defaults to `===` in `Base`.

However, in the current interest of disallowing `==`, we probably want to throw an error in the line of `==(:: DecoratedInterval, ::Interval) = throw(ArgumentError("== is purposely not supported, use equal instead"))`, where `equal` represents the equality function for intervals as described in the standard.
