### ISSUE TITLE
🛣️ The long and treacherous road to compliance with the ITF1788 test suite

### ISSUE THREAD

**Issue by miguelraz** [JuliaIntervals/IntervalArithmetic.jl#225]
I'm opening this issue as a roadmap in order to track what needs to be done in order to achieve compliance with the ITF1788 test suite. It'll update as PRs/issues get handled. This table was obtained by [building the latest test suite (deps: python3, ply, yaml)](https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/master/test/ITF1788_tests/ITF1788_test_generation_instructions.md) and running the test suite manually.

Summary:

|    Road to compliance    	| Tracking issues/PRs? 	| No missing functionality? 	| No Missing tests? 	| Error Free? 	|     Good to go?    	|
|:------------------------:	|:--------------------:	|:-------------------------:	|:-----------------:	|:-----------:	|:------------------:	|
|        abs_rev.jl        	|           [#13](https://github.com/oheim/ITF1788/pull/13)           	|                          	|                  	|      :heavy_check_mark:       	|                    	|
|         atan2.jl         	|       [#15](https://github.com/oheim/ITF1788/pull/15)               	|                         	|                   	|       :heavy_check_mark:      	|                    	|
|         c-xsc.jl         	|                      	|                           	|                   	|             	| :heavy_check_mark: 	|
|         fi_lib.jl        	|                      	|                           	|                   	|      ❌      	|                    	|
| ieee1788-constructors.jl 	|       #219,#221      	|             ❌             	|                   	|             	|                    	|
|  ieee1788-exceptions.jl  	|         #222         	|                           	|                   	|      ❌      	|                    	|
| ieee1788-bool.jl         	| #219                 	|                           	|                   	|        ❌      	|                    	|
|    ieee1788-cancel.jl    	|                      	|                           	|                   	|             	| :heavy_check_mark: 	|
|     ieee1788-class.jl    	|                      	|                           	|         ❌         	|             	|                    	|
|     ieee1788-elem.jl     	|      #219, #223      	|                           	|                   	|      ❌      	|                    	|
|    ieee1788-mul_rev.jl   	|                      	|                           	|         ❌         	|             	|                    	|
|      ieee1788-num.jl     	|         #219         	|                           	|         ❌         	|      ❌      	|                    	|
|    ieee1788-overlap.jl   	|         #224         	|                           	|                   	|      ❌      	|                    	|
|   ieee1788-rec_bool.jl   	|                      	|                           	|                   	|             	| :heavy_check_mark: 	|
|   ieee1788-reduction.jl  	|                      	|                           	|         ❌         	|             	|                    	|
|      ieee1788-rev.jl     	|                      	|                           	|         ❌         	|             	|                    	|
|      ieee1788-set.jl     	|                      	|                           	|                   	|             	| :heavy_check_mark: 	|
|          mpfi.jl         	|                      	|                           	|         ❌         	|      ❌      	|                    	|
|        pow_rev.jl        	|                      	|                           	|         ❌         	|      ❌      	|                    	|

**Comment by ignacio-vc** [comment]
Very handy, thank you. I'll make sure to contribute in short order

**Comment by dpsanders** [comment]
Thanks a lot for this @miguelraz!

**Comment by miguelraz** [comment]
No probs. 3 questions.
1. The PRs for contractors should go into IntervalContractors.jl, right?
2. Missing test sets - how should we generate those for stuff like `atan2` and others? Ping the `ITF1788` repo?
3. Non-ieee1788 files - are they part of the standard? Priority? There's some hairy bugs in the `mpfi.jl` file that seem to, at first glance, cause problems upstream with MPFI.jl. Should we look into those versions 

Tomorrow I will upload the latest versions of the tests to a standalone repo.
Maybe a BinaryBuilder.jl solution is in order later to automatize pulling the test autogeneration script + dependencies, creating the files, and PRing into its own repo.

**Comment by ignacio-vc** [comment]
@miguelraz I could look into automating that, as well as [this other issue in ValidatedNumerics I've been working on](https://github.com/JuliaIntervals/ValidatedNumerics.jl/pull/247)

**Comment by miguelraz** [comment]
Cool beans.
[I uploaded the latest test files here](https://github.com/miguelraz/ieeeITF1788-2005.jl/tree/master/IntervalArithmetic) and will be PRing my changes into that repo for the while being.

**Comment by miguelraz** [comment]
Pending a PR (https://github.com/oheim/ITF1788/pull/15), `atan2.jl` should be good to go testwise.

**Comment by lucaferranti** [comment]
superseeded by https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/465
