### ISSUE TITLE
sup(∅) == -Inf

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#232]
This is surely wrong.

**Comment by dpsanders** [comment]
We should just define `sup(∅) = Inf`. Similarly `inf(∅) = -Inf`.

**Comment by dpsanders** [comment]
The current behaviour is what the Octave package does, but it seems wrong (and caused trouble in actual code). Is this specified in the standard?

**Comment by lbenet** [comment]
I disagree; your proposal corresponds to the entire interval and, in this, we are actually following the standard. Quoting page 6 of the standard, in the definition of *bounds*: "... By convention the empty set has lower bound +∞ and upper bound −∞. Note ±∞ can be bounds of an interval but never members of it."

**Comment by dpsanders** [comment]
Ah so what I'm saying is against the standard...

**Comment by lbenet** [comment]
I think so...

**Comment by dpsanders** [comment]
This just seems very wrong to me. How can sup be < inf ?

**Comment by lbenet** [comment]
I look at it as a trick (or if you want to call it "sentinel") to define an interval which represents "no domain".

**Comment by Kolaru** [comment]
Well if `sup` means `supremum` then it makes sense: mathematically the supremum of *S* is the smallest number bigger or equal than any element of *S*... Very formally for the empty set this indeed yield `sup(∅) = −∞`.

**Comment by lbenet** [comment]
> Well if `sup` means `supremum` then it makes sense: mathematically the supremum of S is the smallest number bigger or equal than any element of S... Very formally for the empty set this indeed yield `sup(∅) = −∞`.

Fully agree with @Kolaru ; the same idea holds for `inf(∅) = ∞`.

**Comment by miguelraz** [comment]
Remember that the standard defines `∅ == Interval(Inf,-Inf)`, so for consistency's sake, taking the supremum means taking the one on the right... yuck. :nauseated_face:

**Comment by dpsanders** [comment]
Closing reluctantly.
