### ISSUE TITLE
nai should be a decorated interval

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#233]
According to [this](https://octave.sourceforge.io/interval/function/nai.html) (and presumably the standard -- I do remember reading something like that).

This would fix some recent issues -- we can leave operations between intervals and decoratedintervals undefined.

**Comment by lbenet** [comment]
You are right; I just checked it and it appears like that in several places.

**Comment by krish8484** [comment]
Implemented in #386
