### ISSUE TITLE
X ∈ X is true when X is an interval

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#247]
```jl
julia> (3..4) ∈ (3..4)
true
```
It seems to me that this should not be true.

**Comment by dpsanders** [comment]
I think `X ∈ Y` should just be an error when X and Y are intervals.

cc @Kolaru

**Comment by lbenet** [comment]
> I think X ∈ Y should just be an error when X and Y are intervals.

I agree; ` X ∈ Y` should be restricted to `X` being a non-interval `Real`. As far as I looked it up, this function should correspond to `isMember(m ,X)` in the standard, which involves a number m and an interval X.

The comparison functions involving two intervals are `==`, `issubset` (`⊆`), `isinterior` (`⪽`), and `isdisjoint`.

**Comment by Kolaru** [comment]
I agree this is not currently correct.

I am in favor of restricting the use of the `in` function (aka `∈`) using the machinery proposed in PR #185, i.e. by defining a list of officially supported type and trait-like syntax to allow user to add custom types to it.

**Comment by dpsanders** [comment]
Fixed by #244.
