### ISSUE TITLE
Efficient n-ary intersection of intervals

### ISSUE THREAD

**Issue by mforets** [JuliaIntervals/IntervalArithmetic.jl#256]
The problem of intersecting a finite number of intervals is well known, see [this SO question](https://stackoverflow.com/questions/4446112/search-for-interval-overlap-in-list-of-intervals). See also [interval trees](https://en.wikipedia.org/wiki/Interval_tree).

Outsourced from [this comment](https://github.com/JuliaDiff/TaylorSeries.jl/pull/195#issuecomment-461058169).

**Comment by dpsanders** [comment]
https://github.com/BioJulia/IntervalTrees.jl

But given just a list of intervals, it seems unlikely that it will be more efficient to build this tree? But maybe it is.

**Comment by mforets** [comment]
Indeed, seems like that structure is suited to find [intersections of parts of the tree](https://biojulia.net/IntervalTrees.jl/stable/man/intersection.html#Intersection-1), or between two such trees, etc.

Since we only care about the entire intersection, how about:

```julia
function intersect_array(Ik::Interval{T}...) where T
    low = maximum(broadcast(x -> x.lo, Ik))
    high = minimum(broadcast(x -> x.hi, Ik))
    if !is_valid_interval(low, high) 
        return emptyinterval(T)
    end
    return Interval(low, high)
end
```

I tried a couple of alternatives (giving `Ik` as a vector argument, writing my own `low, high` loop instead of `broadcast`, using splatting in `min` / `max`), and this is the closer i could get to the custom [intersect_four_fused](https://github.com/JuliaDiff/TaylorSeries.jl/pull/195#issuecomment-461078851):

```julia
julia> @btime intersect_array($I1, $I2, $I3, $I4)
  16.265 ns (0 allocations: 0 bytes)

julia> @btime intersect_four_fused($I1, $I2, $I3, $I4)
  14.776 ns (0 allocations: 0 bytes)
```
I think that this difference is acceptable.

I haven't tried calling it `intersect` and add export it from IntervalArithmetic; i suspect that this will create an ambiguity with the existing binary `intersect(x, y)` that has to be resolved.

**Comment by mforets** [comment]
Well, well.. 

```julia
I100 = [Interval(rand()-1, rand()) for _ in 1:100];

function intersect_array_binary(Ik::Interval{T}...) where T
    Ires = I1
    @inbounds for x in Ik
        Ires = intersect(Ires, x)
        if isempty(Ires)
            return Ires
        end
    end
    return Ires
end
julia> @btime intersect_array($I100...)
10.958 μs (310 allocations: 14.59 KiB)

julia> 
```

**Comment by lbenet** [comment]
I think you can skip the `if` block completely, since you have
```julia
julia> emptyinterval() ∩ (1..2)
∅
```

**Comment by dpsanders** [comment]
I think you can write this as `reduce(intersect, Ik)`

**Comment by dpsanders** [comment]
It shouldn't cause an ambiguity, since the method with 2 arguments is more specific.

**Comment by dpsanders** [comment]
I think a lot of that may be the splatting penalty.

**Comment by dpsanders** [comment]
It works perfectly well to import `Base.intersect` and call this function `intersect`.
