### ISSUE TITLE
Dividing exactly 0 always returns 0.

### ISSUE THREAD

**Issue by Kolaru** [JuliaIntervals/IntervalArithmetic.jl#264]
```jl
julia> 0.0/((-10)..10)
[0, 0]

julia> Interval(0.0)/((-10)..10)
[0, 0]
```

Both should probably return `-Inf..Inf`.

**Comment by dpsanders** [comment]
Ouch. Is this specified in the standard?

**Comment by gwater** [comment]
The standard excludes division by zero, going by Table 9.1. In section 10.5.5 the authors note that reverse multiplication provides an alternative operation, which should for example yield *any real number* in the case of `0/0`.

**Comment by gwater** [comment]
Apparently, this behavior is intended – at least going by [the current code](https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/9a38d80f5eb67da5d8d721fcc0060ec162c55164/src/intervals/arithmetic.jl#L194).

**Comment by Kolaru** [comment]
Returning `-Inf..Inf` seems to be safe i.e. the computation may be unhelpful but will be correct.

The use of [`extended_div`](https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/9a38d80f5eb67da5d8d721fcc0060ec162c55164/src/intervals/arithmetic.jl#L216) should however be encouraged by the documentation, as it implements the 10.5.5. two output division and is probably the better we can do when it comes to division by 0.

**Comment by Kolaru** [comment]
Also there is an interesting discussion of the problem of division by 0 in

*Introduction to Interval Analysis*, R.E. Moore, R.B. Kearfott & M.J. Cloud, SIAM (2009)

in the notes concerning extended interval arithmetic starting at page 125. No definitive answer to the question is given tough.

**Comment by gwater** [comment]
> Returning `-Inf..Inf` seems to be safe i.e. the computation may be unhelpful but will be correct.

Correct in which sense?

**Comment by dpsanders** [comment]
If you take the limit of `(-eps..eps)` / `(-1..1)`  as eps -> 0, the limit is indeed `-Inf..Inf`. 

As far as I can tell, the standard does not specify what to do for division by intervals that contain 0?

I believe we had copied the choice made in the Octave interval package, but maybe that is not the most useful choice.

**Comment by gwater** [comment]
I'm a little concerned because the standard explicitely reserves this behavior (i.e. returning `-Inf..Inf`) for the reverse multiplication operation. Unfortunately, it apparently doesn't specify what division should do instead…

**Comment by Kolaru** [comment]
I meant correct in the sense it should not cause any result to not be valid. I was, however, overlooking the complexity of the issue.

Since, I got a bit more insight into the problem (on a theoretical level). In our representation infinities are never part of an interval, thus

```jl
julia> Inf in -Inf..Inf
false

julia> 1/(0..0)
∅
```

One of the consequence is

```jl
julia> 0*(-Inf..Inf)
[0, 0]
```

But then if we want associativity i.e. `0/(-1..1) == 0 * (1/(-1..1)) == 0 * (-Inf..Inf)` we are forced to use the current definition.

With regard to the standard, excluding infinities from intervals is compliant with the *set based flavor*, the only flavor defined in the standard. To quote the standard about the matter (section 10.2, p.34):

![image](https://user-images.githubusercontent.com/17861033/53897636-dc4dab00-4036-11e9-9907-c19440d27dac.png)

However the division by zero is not defined in this flavor, probably by design, and may thus return an error, `NaI` or an actual value (unless I missed something about the expected result of undefined operations).

Since #254 will have to deal with multiple flavors anyway, this problem will appear for each of them. I think that following the various flavor considered, if makes sense if one of them will error (the strictest one) and one of them will return `-Inf..Inf` (the most lenient).

Also note than the *Cset* flavor (mentionned but not defined in the standard), would handle this case gracefully by allowing infinite numbers to be member of interval (and basing the definition of interval on notions of limits).

**Comment by dpsanders** [comment]
Good point about associativity. Another way to save it (I think) would be to also define
`1 / (0..0)` as `-Inf..Inf`, which makes more sense to me perhaps.

**Comment by Kolaru** [comment]
With regard to the set based flavor it doesn't quite work as only `x = -Inf` and `x = Inf` solve `x*(0..0) == 1` (the definition of the division). But neither solution is in `-Inf..Inf`.

**Comment by dpsanders** [comment]
Sure, but somewhere we need to bend something...
