### ISSUE TITLE
Extended interval arithmetic?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaIntervals/IntervalArithmetic.jl#272]
I noticed that extended interval arithmetic is not implemented:
```julia
julia> 1/Interval(-1,1) # why {x : |x| > 1}?
[-∞, ∞]
```
instead it is done by hand in https://github.com/JuliaIntervals/IntervalRootFinding.jl/blob/99cc0e95885df8e4699f52ffc02df9b8ca748bc6/src/newton.jl#L77

Is there any fundamental limitation preventing this? I guess it is overkill for just Newton iteration, but I'm just curious.

**Comment by lbenet** [comment]
Thanks for reporting. 

We have some functionality on this: `extended_div`:
```julia
julia> extended_div(Interval(1,1), Interval(-1,1))
([-∞, -1], [1, ∞])
```

**Comment by dlfivefifty** [comment]
I guess I was thinking more a special type `ExtendInterval` which lives on the compactified real line. So
```julia
d = ExendedInterval(2,-1) # represents {x : x > 2 or x < -1}
d == 1/ExtendedInterval(-1,2)
3 in d
Inf in d
!(0 in d)
```

**Comment by dpsanders** [comment]
I believe this is known as Kaucher arithmetic. 

An alternative would be to have an IntervalUnion type representing a finite union of intervals, which has also been studied recently (and I have a start on that somewhere).

**Comment by dlfivefifty** [comment]
I think there are use cases for each of these. But it's debatable that they all need to be in this package...

**Comment by dpsanders** [comment]
I agree that this package is probably not the right place for these.

**Comment by lbenet** [comment]
> I agree that this package is probably not the right place for these.

I am not sure that I agree with this opinion; as @dlfivefifty says, it is debatable. For me, Julia is precisely the language to implement different flavors of interval arithmetic; see #271.
