### ISSUE TITLE
Rational powers of intervals are broken

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#276]
```
julia> x = 3..4
[3, 4]

julia> x^(1//3)
ERROR: MethodError: ^(::Interval{Float64}, ::Rational{Int64}) is ambiguous. Candidates:
```
There is currently an implementation in IntervalContractors, referred to [here](https://github.com/JuliaIntervals/IntervalContractors.jl/pull/27), but that should be moved here (and possibly improved).

**Comment by dpsanders** [comment]
This should possibly / probably use the nth root function provided by MPFR: see 
the `mpfr_rootn_ui` function in the [MPFR docs](https://www.mpfr.org/mpfr-current/mpfr.html)

**Comment by dpsanders** [comment]
cc @yashrajgupta

**Comment by dpsanders** [comment]
@yashrajgupta It would be good to get this fixed ASAP.

**Comment by yashrajgupta** [comment]
@dpsanders  We have `function ^(a::Interval{BigFloat}, r::Rational{S})` but it doesn't give the expected results and the `^(x::Interval{Float64}, r::Rational)` also gives the same output. Shall we define a single function `^(x::Interval{T} , r::Rational)`. (though I dont know how).

**Comment by dpsanders** [comment]
What do you mean when you say it "doesn't give the expected results"?

I suggested a way to do it in the 2nd message in this thread: use the MPFR function for the nth root.
This should probably be added to base Julia but you can start by trying it out here.

Since it's a C function, you will need to copy how it's done in `mpfr.jl` in base Julia to see how to call it.

**Comment by yashrajgupta** [comment]
Sorry I thought we were talking about the accuracy of rational power function. But the code you stated in the first message of this thread works in my package.
```jl
julia> x = 3..4
[3, 4]

julia> x ^ (1//3)
[1.44224, 1.58741]
```

**Comment by dpsanders** [comment]
Yes that's what we're talking about. How is a rational power *defined*? 

Yes in some environments it works for me and in others it gives an ambiguity. We need to track that down. E.g. what happens with the master branch? With the released version?

In any case, just defining an explicit rational power function should be enough to remove possible ambiguities. We just have to be careful about how it's done.

**Comment by dpsanders** [comment]
Current behaviour:
```jl
julia> x^(1//3)
[1.44224, 1.58741]
```
