### ISSUE TITLE
Use atan from CRlibm

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#296]
We seem to be using atan from MPFR.

**Comment by lucaferranti** [comment]
> It seems than both atan and atan2 are supported in CRlibm https://core-math.gitlabpages.inria.fr/

that's the link to core math (successor of crlibm), according to the second table, it seems atan2 is not supported? (first column float32 second column float64).

![image](https://user-images.githubusercontent.com/49938764/197859255-2918ccb9-f6a0-40fb-a759-680457e6d236.png)

**Comment by OlivierHnt** [comment]
AFAICT, this issue is fixed on master.
