### ISSUE TITLE
Range of atan

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#297]
What happens if a interval spans values of the angle that cross pi or -pi?

**Comment by lbenet** [comment]
`atan` is defined in the whole real line, so `atan(entireinterval())` should return the interval `-pi/2 .. pi/2`, as it currently does.

If you meant `tan` and you care about crossing `pi/2`, it should return `[-∞, ∞]` as it does.

Both properties work also fine for bigfloats.

**Comment by lbenet** [comment]
Fixed by #338
