### ISSUE TITLE
isfinite(): every interval contains only finite members

### ISSUE THREAD

**Issue by gwater** [JuliaIntervals/IntervalArithmetic.jl#309]
According to the IEEE standard, intervals must not contain infinities. Nevertheless, they can have infinite bounds.

Therefore, `isfinite()` should return `true` in all cases, except NaN-intervals and empty intervals.

Currently, `isfinite()` checks for finite bounds:
```
isfinite(x::Interval) = isfinite(x.lo) && isfinite(x.hi)
```
https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/1114b4c/src/intervals/special.jl#L37

**Comment by dpsanders** [comment]
Thanks for the observation. 

I guess this is another of those cases where it depends if an interval is a number or not.

In floating point, `Inf` basically means "anything larger than the largest representable `Float`. The interval `3..\infty` contains something larger than that, so in that sense is "infinite".

**Comment by dpsanders** [comment]
Also, I don't think anything actually changes if you regard the interval `3..Inf` as actually containing the "number" `Inf` (i.e. being a closed interval) or not (semi-open).

**Comment by dpsanders** [comment]
The current definition of `isinf` (i.e. checking `isentire`) is also rather doubtful.
It seems to me that `isinf` for an interval should return true if either endpoint is infinite.

All of these problems stem from the fact that we are talking about sets rather than values, and most algorithms found "in the wild" think about operating only on numbers.

This makes me think increasingly that @gwater is correct to say that intervals should error when thrown into random numerical code...

**Comment by gwater** [comment]
> This makes me think increasingly that @gwater is correct to say that intervals should error when thrown into random numerical code...

I've recently found that this is also [how Boost handles binary comparisons](https://www.boost.org/doc/libs/1_70_0/libs/numeric/interval/doc/comparisons.htm).

**Comment by dpsanders** [comment]
By default yes, but you can also choose different behaviour - see "other comparisons" in that link.

**Comment by Kolaru** [comment]
As discussed in #264, including or not `Inf` in the interval matters in several corner cases. Typically it changes the result of `0 * (3..Inf)`, since `0 * [3, Inf] == [0, Inf]` (closed), but `0 * [3, Inf) == 0` (semi-open).

**Comment by OlivierHnt** [comment]
On master branch we chose to be very conservative with boolean functions to prevent silent errors. Using Interval as a drop-in replacement of a Number in a code should yield an error.
In this regard, the functions `isfinite`, etc. are no longer intended to be supported.
