### ISSUE TITLE
Define `any(isinf, x)` 

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#311]
To emphasise the set nature of intervals, perhaps we should overload

`any(isinf, x::Interval)`

to mean that there exists an infinite value in the set.

Of course, it is hard to do this for an arbitrary predicate `f` in

`any(f, x::Interval)`

-- this is basically what IntervalConstraintProgramming does.

But we can do it for special functions like `isinf`.

**Comment by lbenet** [comment]
Not sure if this helps, but we have `isunbounded(::Interval)`

**Comment by lucaferranti** [comment]
discussed with @lbenet and @Kolaru that we probably don't want to overload `any` for specific functions. Can reopen if someone wants to
