### ISSUE TITLE
assign operator ≼ to precedes()

### ISSUE THREAD

**Issue by gwater** [JuliaIntervals/IntervalArithmetic.jl#314]
there is already ≺ for strictprecedes(), so this would be a natural extension, allowing infix notation

**Comment by dpsanders** [comment]
`?≼` in the REPL shows that this is typed as `\preccurlyeq`,  which is unfortunately painful.

**Comment by dpsanders** [comment]
Although `\precc<TAB>` works.

Perhaps this should be added to base Julia?

**Comment by gwater** [comment]
> `?≼` in the REPL shows that this is typed as `\preccurlyeq`, which is unfortunately painful.

I agree, I just copied the operator from a unicode table. I'm glad there is a way at least to type it in the REPL.

**Comment by lbenet** [comment]
Closed by #322
