### ISSUE TITLE
convert with same type does not use the correct method

### ISSUE THREAD

**Issue by schillic** [JuliaIntervals/IntervalArithmetic.jl#317]
I noticed a recent problem when converting intervals.
The relevant definitions are here:

https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/1516c5e1ca8e088aeafa9574072512aa2df241fb/src/intervals/conversion.jl#L19-L20

To me they look correct, and I think until recently they worked as expected. In particular, the first method should fire if source and target type are identical. Below are the results in a fresh environment with Julia v1.2.0-rc2:

```julia
(v1.2) pkg> st
    Status `~/.julia/environments/v1.2/Project.toml`
  [d1acc4aa] IntervalArithmetic v0.16.0

julia> using IntervalArithmetic

julia> N = Float64; i = N(0) ± N(1)
[-1, 1]

julia> convert(typeof(i), i)
[-1, 1]

julia> @which convert(typeof(i), i)
convert(::Type{Interval{T}}, x::Interval) where T in IntervalArithmetic at .julia/packages/IntervalArithmetic/4e8KJ/src/intervals/conversion.jl:20
```

So the wrong method is used (the more general one). With `Rational`s this even crashes.

```julia
julia> N = Rational{Int}; i = N(0) ± N(1)
[-1//1, 1//1]

julia> convert(typeof(i), i)
ERROR: MethodError: no method matching atomic(::Type{Interval{Rational{Int64}}}, ::Interval{Rational{Int64}})
```
I realized this in a recent rebase of a pull request in Julia v1.0 and v1.1. The build was green before, and since this was after your latest release, the problem is probably not on your side. But I am out of ideas.
Note that this works:
```julia
julia> @which convert(Rational{Int}, 1//1)
convert(::Type{T}, x::T) where T<:Number in Base at number.jl:6
```

**Comment by lbenet** [comment]
I reproduce both problems on Julia 1.1.1. The second problem is understandable (lack of a method)...

**Comment by schillic** [comment]
> The second problem is understandable (lack of a method)...

True, but it only goes there because it does not pick the correct method in line 19...

**Comment by dpsanders** [comment]
This is a weird bug. I don't know why it's happening, but I have a fix in #320.

This should probably be reported as a Julia bug.

**Comment by schillic** [comment]
Thanks a lot!
Since it happened all of a sudden, I suspect that some of your dependencies committed type piracy. I did not update my Julia version.

**Comment by dpsanders** [comment]
Reported on JuliaLang here:
https://github.com/JuliaLang/julia/issues/32884

**Comment by dpsanders** [comment]
This happens with no other packages loaded, so I don't think any dependencies are involved?

**Comment by schillic** [comment]
Right, it's just a mystery.

**Comment by dpsanders** [comment]
Jeff answered in the above issue. 

Did this actually cause any problems for you?

**Comment by schillic** [comment]
Yes, because of the `Rational`s. And it's also less efficient of course.

**Comment by lbenet** [comment]
So, should we restrict the types always?

**Comment by dpsanders** [comment]
Maybe we should restrict the types, but that's a lot of code to work through...

**Comment by dpsanders** [comment]
The `Rational` case works now after #320 . Thanks for the report!
