### ISSUE TITLE
Implement reverse mode elementary functions

### ISSUE THREAD

**Issue by Kolaru** [JuliaIntervals/IntervalArithmetic.jl#323]
Unless I've missed a file somewhere, the reverse mode elementary functions required for the set based flavor by the IEEE Std 1788-2015 (section 10.5.4) are not implemented.

**Comment by dpsanders** [comment]
They are in the IntervalContractors.jl package.

**Comment by lbenet** [comment]
I think we should perhaps bring them here, since they are required by the standard.

**Comment by dpsanders** [comment]
I think we should just resurrect ValidatedNumerics.jl (or some similar name) and have it export both packages.

**Comment by lbenet** [comment]
I like the idea of resurrecting ValidatedNumerics.jl, but still think that IntervalArithmetic.jl is the right place for the reverse-mode elementary functions. IntervalContractors.jl will be essentially unchanged (except for releasing a new minor(?) version) since it imports IntervalArithmetic.jl.

**Comment by dpsanders** [comment]
I personally feel that the reverse-mode functions are really so far away in concept and style from the rest of interval arithmetic that they belong in a separate julia package. 

Are they included in the simplified standard? I don't remember but think not?

**Comment by Kolaru** [comment]
They are not included in the simplified standard (see Annex A of the simplified standard, listing all things only requested in the full standard).

In regard of compliance with the full standard, where the functions are defined is probably irrelevant. Saying somethign like "`IntervalArithmetic.jl`, together with `IntervalContractors.jl`, sastifies the standard" sounds fine for me, as long at it is documented.

**Comment by lbenet** [comment]
> I personally feel that the reverse-mode functions are really so far away in concept and style from the rest of interval arithmetic that they belong in a separate julia package.

I still agree with the *concept* part, since these functions are proposed in the full standard. If it is a question of style, maybe we should simply include a naive form here (independently coded), perhaps even use a different naming convention, and even not exporting them, to avoid collisions. 

In my opinion, it sounds nicer "IntervalArithmetic.jl sastifies the standard", which serves as a basic library to build other things on top of it (as it is now).

**Comment by Kolaru** [comment]
I'm reopening this issue because while we decided to not have it in IntervalArithmetic.jl itself (IIRC), it still needs to be documented properly.

I believe we need a "Compliance with standard" section in the doc.
