### ISSUE TITLE
Calculation Runs Forever?

### ISSUE THREAD

**Issue by caseykneale** [JuliaIntervals/IntervalArithmetic.jl#327]
Was trying this package out and found a weird simple case that appears to run forever?

```
using IntervalRootFinding, IntervalArithmetic, StaticArrays
line1( x ) = 2.0 * (x^2.0)
line2( x ) = 4.0*x - 2.0
fun(x) = line1(x) - line2(x)
time rts = roots(fun, Interval( -10..10 ) )
```

Am I missing something? Why does this happen?

**Comment by dpsanders** [comment]
This is a problem with IntervalRootFinding.jl and should be reported there.

The function has a double root, but even so should not lead to an infinite calculation. I will check later when I have a moment. Thanks for reporting!

**Comment by dpsanders** [comment]
Cc @kolaru

**Comment by caseykneale** [comment]
Feel free to close this issue I'll go file an issue over there! Thank you
