### ISSUE TITLE
`setrounding` uses old-style `warn` and `error` functions

### ISSUE THREAD

**Issue by ssfrr** [JuliaIntervals/IntervalArithmetic.jl#328]
This is on both `master` and the `nonrecursive_powers` branch.

https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/nonrecursive_powers/src/intervals/rounding.jl#L315-L319

I hit this because I was calling `setrounding(Interval, :none)` in my main package body instead of from an `__init__()` function, which causes issues during precompilation.

**Comment by Kolaru** [comment]
`setrounding` has been removed on master.
