### ISSUE TITLE
Does not work with IEEEFloat16

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#331]
We should make this work with 

https://github.com/vchuravy/IEEEFloat16.jl

(half-precision, i.e. 16-bit floats).

We can do this using ErrorfreeArithmetic.

For higher precision it might be possible to use DoubleFloats or Float128, but maybe error-free arithmetic won't work properly there?

**Comment by dpsanders** [comment]
It "works" on the GPU. The IEEEFloat16 package itself does not work correctly on the CPU.

**Comment by OlivierHnt** [comment]
Closing this since the [IEEEFloat16.jl](https://github.com/vchuravy/IEEEFloat16.jl) package has been archived.
