### ISSUE TITLE
Use SafeEFT for rounding

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#341]
https://github.com/JuliaMath/AccurateArithmetic.jl/issues/8

**Comment by OlivierHnt** [comment]
What is the status of this issue? Has it been resolved?

**Comment by dpsanders** [comment]
We ended up using https://github.com/matsueushi/RoundingEmulator.jl so I think this has been resolved if that is still being used.

**Comment by OlivierHnt** [comment]
Perfect, this is what is still being used 🙂
