### ISSUE TITLE
`log1p(interval(x))` not working for `-1 < x <= 0`

### ISSUE THREAD

**Issue by ericphanson** [JuliaIntervals/IntervalArithmetic.jl#342]
Semantically `log1p(x) = log(1 + x)`, so it's domain should be `x > -1`, but here it's domain is set as starting from zero: https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/fd7bee93ea56e260924ee8ec670af674b5f26936/src/intervals/functions.jl#L299

**Comment by ericphanson** [comment]
Making the obvious modifications, `0` to `-1` and `zero(T)` to `-one(T)`, I find
```julia
function Base.log1p(a::Interval{T}) where T
    domain = Interval{T}(-1, Inf)
    a = a ∩ domain
    (isempty(a) || a.hi ≤ -one(T)) && return emptyinterval(a)
    IntervalArithmetic.@round( log1p(a.lo), log1p(a.hi) )
end
```
works fine for me. I can make a PR if adding that method would be how you want to go.

**Comment by lbenet** [comment]
Good catch! Thanks for noticing!

I have another question though: `log1p(x)` is supposed to be an accurate evaluation for log(1+x). Though it is not written, I guess that this also means that `x` is small enough. Have you checked the consistency (and diameter) of the intervals produced by `log1p(x)` and `log(1+x)`?

**Comment by ericphanson** [comment]
Hmm, do you have a standard way of comparing? I went for the following attempt:

```julia
using IntervalArithmetic, DataFrames

function Base.log1p(a::Interval{T}) where T
    domain = Interval{T}(-1, Inf)
    a = a ∩ domain
    (isempty(a) || a.hi ≤ -one(T)) && return emptyinterval(a)
    IntervalArithmetic.@round( log1p(a.lo), log1p(a.hi) )
end

log1p_manual(x) = log(1 + x)

function compare(f, g; scale = 1.0)
    a, b = scale*(1-2rand()), scale*(1-2rand())
    if b < a
        a,b = b,a
    end
    X = interval(a,b)
    dX = diam(X)
    df = diam(f(X))
    dg = diam(g(X))
    return (df=df, dg=dg, diff=dg-df, dX=dX)
end

data = DataFrame([ compare(log1p, log1p_manual, scale = 1e-5) for _ = 1:1000 ])
describe(data)[:,1:5]
```

With `scale=1e-5`, meaning intervals near 0, I get
```julia
│ Row │ variable │ mean        │ min         │ median      │ max         │
│     │ Symbol   │ Float64     │ Float64     │ Float64     │ Float64     │
├─────┼──────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│ 1   │ df       │ 7.01749e-6  │ 1.51717e-9  │ 6.29395e-6  │ 1.91602e-5  │
│ 2   │ dg       │ 7.01749e-6  │ 1.51717e-9  │ 6.29395e-6  │ 1.91602e-5  │
│ 3   │ diff     │ 1.65571e-16 │ 1.13807e-17 │ 1.59299e-16 │ 4.27829e-16 │
│ 4   │ dX       │ 7.01749e-6  │ 1.51716e-9  │ 6.29393e-6  │ 1.91602e-5  │
```
The `dX` row tells us about the diameters of the input intervals (which are small), the `diff` row is all positive, meaning `log1p` is getting slightly tighter intervals, but the difference is small. (Note `f=log1p` and `g=log1p_manual`). However, if we take `scale=1e-20`, we see the difference persists, and is now large compared to the size of the intervals:
```julia
│ Row │ variable │ mean        │ min         │ median      │ max         │
│     │ Symbol   │ Float64     │ Float64     │ Float64     │ Float64     │
├─────┼──────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│ 1   │ df       │ 6.53401e-21 │ 1.30972e-23 │ 5.6561e-21  │ 1.93092e-20 │
│ 2   │ dg       │ 2.47802e-16 │ 1.11022e-16 │ 2.22045e-16 │ 3.33067e-16 │
│ 3   │ diff     │ 2.47795e-16 │ 1.11013e-16 │ 2.22045e-16 │ 3.33067e-16 │
│ 4   │ dX       │ 6.53401e-21 │ 1.30972e-23 │ 5.6561e-21  │ 1.93092e-20 │
```
So for `x` very small, it's a clear with for `log1p` (as we should expect).

With `scale=1`, I get
```julia
│ Row │ variable │ mean     │ min        │ median   │ max     │
│     │ Symbol   │ Float64  │ Float64    │ Float64  │ Float64 │
├─────┼──────────┼──────────┼────────────┼──────────┼─────────┤
│ 1   │ df       │ 1.08267  │ 2.24121e-5 │ 0.762508 │ 8.15324 │
│ 2   │ dg       │ 1.08267  │ 2.24121e-5 │ 0.762508 │ 8.15324 │
│ 3   │ diff     │ 0.0      │ 0.0        │ 0.0      │ 0.0     │
│ 4   │ dX       │ 0.694117 │ 3.8343e-5  │ 0.622148 │ 1.95411 │
```

To consider `x` large, I changed the function a bit to only scale the positive part (since we can't let the argument of the log become negative). This is given by
```julia
function compare_large(f, g; scale = 1.0)
    a, b = scale*rand() - rand(), scale*rand() - rand()
    if b < a
        a,b = b,a
    end
    X = interval(a,b)
    dX = diam(X)
    df = diam(f(X))
    dg = diam(g(X))
    return (df=df, dg=dg, diff=dg-df, dX=dX)
end

data_large = DataFrame([ compare_large(log1p, log1p_manual, scale = 100.0) for _ = 1:1000 ])
describe(data_large)[:,1:5]
```
This gives
```julia
│ Row │ variable │ mean        │ min         │ median   │ max         │
│     │ Symbol   │ Float64     │ Float64     │ Float64  │ Float64     │
├─────┼──────────┼─────────────┼─────────────┼──────────┼─────────────┤
│ 1   │ df       │ 0.96675     │ 0.000192499 │ 0.680511 │ 6.85268     │
│ 2   │ dg       │ 0.96675     │ 0.000192499 │ 0.680511 │ 6.85268     │
│ 3   │ diff     │ 5.10703e-18 │ 0.0         │ 0.0      │ 4.44089e-16 │
│ 4   │ dX       │ 34.1959     │ 0.011982    │ 30.0191  │ 98.2385     │
```

So negligible differences except for `x` very small, in which case `log1p` does what you want it to do. Note you do pay a little bit for the accuracy for  non-tiny `x`:
```julia
julia> using BenchmarkTools

julia> x = .1..0.2
[0.0999999, 0.200001]

julia> @btime log1p($x)
  114.929 ns (0 allocations: 0 bytes)
[0.0953101, 0.182322]

julia> @btime log1p_manual($x)
  76.731 ns (0 allocations: 0 bytes)
[0.0953101, 0.182322]
```
But for very small `x`, it's faster too:
```julia
julia> x = interval(1e-20*rand())
[8.08992e-21, 8.08993e-21]

julia> @btime log1p($x)
  16.172 ns (0 allocations: 0 bytes)
[8.08992e-21, 8.08993e-21]

julia> @btime log1p_manual($x)
  275.235 ns (0 allocations: 0 bytes)
[0, 2.22045e-16]
```

**Comment by lbenet** [comment]
`log` is a monotonous function, so the interval evaluation `log(X)` is essentially an evaluation on the borders of `X`, *plus* correct rounding; correct rounding is managed by CRlibm (for Float64). I have to think a bit more about your results... 

In any case, I think it's correct to have `domain = Interval{T}(-1, Inf)` for `log1p`...

**Comment by dpsanders** [comment]
Good catch indeed. 

As far as I understand it, `log1p` is supposed to be defined and correct for all `x >= -1`, but is particularly accurate for small `x`.

Note that there is a correctly rounded version of `log1p` in CRlibm. I presume we already use this?

**Comment by dpsanders** [comment]
Ah sorry, you already wrote about CRlibm.

**Comment by dpsanders** [comment]
Yes we already use it, but the domain should be corrected.
