### ISSUE TITLE
Declare `IntervalBox` as subtype of `AbstractArray`?

### ISSUE THREAD

**Issue by ArjunNarayanan** [JuliaIntervals/IntervalArithmetic.jl#350]
Would it make sense to declare `IntervalBox <: AbstractVector`? Or alternatively `IntervalBox <: AbstractIntervalBox <: AbstractVector`

https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/27cf9f47a9a1c4b5f566b96a1e0a5853a75ad68c/src/multidim/intervalbox.jl#L6

I ran into an error trying to evaluate a function-like object that accepts arrays as arguments. Example:

```
using DynamicPolynomials, IntervalArithmetic

@polyvar x y
box = IntervalBox(-1..1,2)

p = x^2 + 2y^2 + 3x*y
println(p([1,2]))   # 15
println(p(box))     # MethodError: no method matching (::Polynomial{true,Int64})(::IntervalBox{2,Float64})
```

**Comment by mforets** [comment]
Try [splatting](https://docs.julialang.org/en/v1/manual/faq/#What-does-the-...-operator-do?-1) the domain:

```julia
julia> p(box...)
[-3, 6]
```

**Comment by ArjunNarayanan** [comment]
Oops, didn't think of that. Works well, thanks!
