### ISSUE TITLE
Tests failling in nightly

### ISSUE THREAD

**Issue by lbenet** [JuliaIntervals/IntervalArithmetic.jl#360]
I just noticed that tests are failing in nightly; see [this travis output](https://travis-ci.org/JuliaIntervals/IntervalArithmetic.jl/jobs/648433766#L320). The problem seems to be that Base is *also* exporting `isdisjoint`, which makes that `the function is not unambiguously recognized. See also [NanosoldierReports](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_date/2020-01/13/report.md) which runs daily, in the list of packages that failed previously.

**Comment by gwater** [comment]
I think the right solution would be to import and extend `isdisjoint` since the usage in `IntervalArithmetic` matches the specification in the manual, so something like:
```jl
if VERSION >= v"1.5"
	import Base: isdisjoint
end
```

**Comment by dpsanders** [comment]
Maybe we actually need to find the v"1.5-dev100" or whatever it is.
