### ISSUE TITLE
Make this software citable?

### ISSUE THREAD

**Issue by mfherbst** [JuliaIntervals/IntervalArithmetic.jl#371]
I'm currently writing up a publication, where we are using IntervalArithmetic.jl and I would love to cite all the great people contributing to this package! Have you considered making this software citable? E.g. using https://zenodo.org/?

Otherwise: Is there any other publication related to IntervalArithmetic.jl, which I could perhaps cite to give some credit?

**Comment by dpsanders** [comment]
Thanks for your comment @mfherbst!
Yes we should definitely do this. We are about to release a new minor version so that would be a good time to do so.

**Comment by newptcai** [comment]
You need to do the git tag manually on github.com manually. Otherwise you don’t get a doi.

**Comment by dpsanders** [comment]
I had forgotten that we already had enabled Zenodo on the repo:

https://zenodo.org/account/settings/github/repository/JuliaIntervals/IntervalArithmetic.jl

I have just released version 0.17 so you should wait until that appears there.

**Comment by newptcai** [comment]
![Screenshot from 2020-04-14 23-59-38](https://user-images.githubusercontent.com/982197/79278465-04e7db80-7eac-11ea-97f5-afdd0831f7d1.png)

**Comment by dpsanders** [comment]
Sorry, try

https://zenodo.org/record/3727070

**Comment by mfherbst** [comment]
Cool. If I'd only known earlier :smile:
