### ISSUE TITLE
Support gamma function 

### ISSUE THREAD

**Issue by newptcai** [JuliaIntervals/IntervalArithmetic.jl#372]
I just noticed that gamma function is not supported now. It would be convenient to compute it with interval arithmetic.

**Comment by dpsanders** [comment]
I believe that Siegfried Rump has a (recent?) paper on this if you would like to implement it.

**Comment by dpsanders** [comment]
Actually I think this is implemented in ArbReals.jl, so we could interface to that.

And MPFR has it, so that's another possibility.

**Comment by dpsanders** [comment]
```jl
julia> setrounding(BigFloat, RoundUp) do
           gamma(big(3.1))
           end
2.197620278392477241861883064799099618736560622889775553822745587224982087167695

julia> setrounding(BigFloat, RoundDown) do
           gamma(big(3.1))
           end
2.19762027839247724186188306479909961873656062288977555382274558722498208716766
```

**Comment by newptcai** [comment]
> Actually I think this is implemented in ArbReals.jl, so we could interface to that.
> 
> And MPFR has it, so that's another possibility.

Arb has many special functions implemented. Interfacing it would certainly make IntervalArithemic more convenient. I vote for this!

**Comment by dpsanders** [comment]
Actually I would prefer to put the special functions and the `ArbNumerics` interface in 

https://github.com/JuliaIntervals/IntervalSpecialFunctions.jl

**Comment by dpsanders** [comment]
cc @JeffreySarnoff for guidance.

**Comment by JeffreySarnoff** [comment]
I could write something which given `ArbNumerics.fn, lo, hi, precision_in_bits` would return `lo, hi` that is inclusory at that precision.  Does IntervalArithmetic accept precisions > Float64?

**Comment by JeffreySarnoff** [comment]
working on this notion .. will post something here sometime soon

**Comment by dpsanders** [comment]
That would be great thanks! Yes also accept BigFloat.

I'm fact in prínciple we can use any floating point type with good enough rounding, but for example I don't think Double Floats have the rounding we need. 

We could even use ArbFloats. Although I think a bit of work would be needed for any new float type.

**Comment by JeffreySarnoff** [comment]
```
using IntervalArithmetic
import SpecialFunctions
import ArbNumerics
using ArbNumerics: ArbFloat, setinterval, lowerbound, upperbound,
                   gamma, zeta, elliptic_k

SpecialFunctions.gamma(x::Interval{T}) where T =
    specialfunction(gamma, x)

SpecialFunctions.zeta(x::Interval{T}) where T =
    specialfunction(zeta, x)

ArbNumerics.elliptic_k(x::Interval{T}) where T =
    specialfunction(elliptic_k, x)


function specialfunction(fn, x::Interval{T}) where T
    y = fn(arbreal(x))
    lo, hi = lowerbound(y), upperbound(y)
    ylo, yhi = T(lo), T(hi)
    return Interval{T}(ylo, yhi)
end
    

function arbreal(x::Interval)
    resetprecision()
    lo = ArbFloat(x.lo)
    hi = ArbFloat(x.hi)
    return setinterval(lo, hi)
end

function resetprecision()
    _, prec = precision(Interval)
    setprecision(ArbFloat, prec)
    return nothing
end


xlo, xhi = prevfloat(0.5), 0.5;
x = @interval(xlo, xhi);

gamma_x = gamma(x)
zeta_x = gamma(x)
elliptick_x = elliptic_k(x)
```

**Comment by JeffreySarnoff** [comment]
https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/372#issuecomment-613246005

**Comment by newptcai** [comment]
What does this two lines do?
````
xlo, xhi = prevfloat(0.5), 0.5;
x = @interval(xlo, xhi);
````

Also, there are many functions in Arb. Can we maybe meta programming this part?

````
SpecialFunctions.gamma(x::Interval{T}) where T =
    specialfunction(gamma, x)

SpecialFunctions.zeta(x::Interval{T}) where T =
    specialfunction(zeta, x)

ArbNumerics.elliptic_k(x::Interval{T}) where T =
    specialfunction(elliptic_k, x)
````

**Comment by JeffreySarnoff** [comment]
@interval should have been Interval .. It is corrected above 
(just run the lines to see what it does)

The functions I showed were to demonstrate how its done.
Once the approach is agreed, the functions can be done in 2 @eval loops.

**Comment by dpsanders** [comment]
Thanks @JeffreySarnoff!

So this does not actually use intervals from Arb? Wouldn't that be required for correctness?
I don't have any experience with Arb unfortunately.

**Comment by dpsanders** [comment]
Ah, maybe it's a printing issue?
When I do `arbreal(3.1)` I don't see an interval.

**Comment by dpsanders** [comment]
```
julia> arbreal(interval(prevfloat(3.1), nextfloat(3.1)))
3.1
```

**Comment by dpsanders** [comment]
OK, I read the docs, sorry...

**Comment by dpsanders** [comment]
OK this looks fantastic! As I said, I would prefer to put this in `IntervalSpecialFunctions.jl`, which I think is not currently registered.

There are some details we should take care of about precision; `precision(Interval)` works only for `BigFloat` intervals.

I can add this to `IntervalSpecialFunctions.jl` unless somebody else would like to? If depends if @JeffreySarnoff would like the commits under his name.

**Comment by JeffreySarnoff** [comment]
Let me have the day to ruminate -- just to be sure I have not overlooked something.

**Comment by JeffreySarnoff** [comment]
I like the current realization (see updated [code and example](https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/372#issuecomment-613246005).  Any comments before I cull routines and deal with different arities?

**Comment by dpsanders** [comment]
Just that we should separate out the case of Float64, where we know the precision, and BigFloat. We can just check the precision of a BigFloat interval in the moment and use the corresponding precision in Arb.

**Comment by JeffreySarnoff** [comment]
for comment
```

using IntervalArithmetic
import SpecialFunctions
import ArbNumerics
using ArbNumerics: ArbFloat, setinterval, lowerbound, upperbound


# number of bits that suffices to alter the least signfiicant digit
#   used as prevfloat(x, DigitBits), nextfloat(x, DigitBits)
const DigitBits = ceil(Int, log2(10))


function specialfunction(fn, x::Interval{T}) where T
     y = fn(arbreal(x))
     lo, hi = lowerbound(y), upperbound(y)
     ylo, yhi = T(lo), T(hi)
     return Interval{T}(ylo, yhi)
end

function arbreal(x::Interval{T}) where T
     setprecision(ArbFloat, T)
     lo = prevfloat(ArbFloat(x.lo), DigitBits) # assure least significant    
     hi = nextfloat(ArbFloat(x.hi), DigitBits) # decimal digit changes
     return setinterval(lo, hi)
end
     
Base.setprecision(::Type{ArbFloat}, ::Type{Float64}) =
    setprecision(ArbFloat, 53)
Base.setprecision(::Type{ArbFloat}, ::Type{Float32}) =
    setprecision(ArbFloat, 24)
Base.setprecision(::Type{ArbFloat}, ::Type{BigFloat}) =
    setprecision(ArbFloat, precision(BigFloat))


# functions of 1 arg exported by SpecialFunctions and ArbNumerics
for F in (:airyai, :airyaiprime, :airybi, :airybiprime,
          :besselj0, :besselj1, :bessely0, :bessely1,
          :erf, :erfc, :erfi,
          :gamma, :lgamma, :digamma,:trigamma,
          :eta, :zeta)
    @eval SpecialFunctions.$F(x::A) where {T, A<:Interval{T}} =
          specialfunction($F,x)
end

# functions of 1 arg exported by both with distinct names
for F in (:cosint, :sinint, :ellipk, :ellipe)
    @eval SpecialFunctions.$F(x::A) where {T, A<:Interval{T}} =
          specialfunction($F,x)
end
for F in (:ci, :si, :elliptic_k, :elliptic_e)
    @eval ArbNumerics.$F(x::A) where {T, A<:Interval{T}} =
          specialfunction($F,x)
end

# functions of 1 arg exported by ArbNumerics only
for F in (:chi, :shi, :ei, :xi,  :lambertw)
    @eval ArbNumerics.$F(x::A) where {T, A<:Interval{T}} =
          specialfunction($F,x)
end

# functions of a 2 args exported by ArbNumerics only
for F in (:elliptic_pi, :elliptic_pi2, :polylog,
          :hypergeometric_0F1, :regular_hypergeometric_0F1)
    @eval ArbNumerics.$F(a::A, b::A) where {T, A<:Interval{T}} =
          specialfunction($F, a, b)
end

# functions of a 3 args exported by ArbNumerics only
for F in (:hypergeometric_1F1, :regular_hypergeometric_1F1)
    @eval ArbNumerics.$F(a::A, b::A, z::A) where {T, A<:Interval{T}} =
          specialfunction($F, a, b, z)
end

# functions of a 4 args exported by ArbNumerics only
for F in (:hypergeometric_2F1, :regular_hypergeometric_2F1)
    @eval ArbNumerics.$F(a::A, b::A, c::A, z::A) where
                                   {T, A<:Interval{T}} =
          specialfunction($F, a, b, c, z)
end

function __init__()
    # provide padding for prevfloat, nextfloat in arbreal()
    extrabits = ArbNumerics.ExtraBits[] + DigitBits
    ArbNumerics.setextrabits(extrabits)
    return nothing
end
```

**Comment by JeffreySarnoff** [comment]
@dpsanders This is for your use with IntervalSpecialFunctions ✈️.

**Comment by dpsanders** [comment]
Moving to IntervalSpecialFunctions.jl package.
