### ISSUE TITLE
Parsing intervals from strings

### ISSUE THREAD

**Issue by lucaferranti** [JuliaIntervals/IntervalArithmetic.jl#383]
Intervals using `..` cannot be parsed properly from strings.

```julia
julia> I"1..2"
[1, 1]

julia> @interval "1..2"
[1, 1]

@biginterval "1..2"
[1, 1]₂₅₆
```
Obtained  using Julia 1.4.0, IntervalArithmetic v0.17.3

**Comment by OlivierHnt** [comment]
On master

```Julia
julia> I"1..2"
┌ Warning: invalid input, empty interval is returned
└ @ IntervalArithmetic ~/.julia/dev/IntervalArithmetic/src/parsing.jl:83
∅
```

Presumably we do not want to conflate the syntax rules for parsing a `String` with the constructor syntax. E.g. `I"interval(1, 2)"` or `I"1 ± 2"` also returns an empty interval.
