### ISSUE TITLE
Equality for decorated intervals

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#394]
Currently we have
```
julia> DecoratedInterval(1..2, com) ==  DecoratedInterval(1..2, trv)
true
```

Is this specified in the standard?

cc @krish8484

**Comment by krish8484** [comment]
According to section 11.5.3 of the standard, "For decorations, comparison operations for equality = and its negation shall be provided, as well as comparisons >,<,≥,≤ with respect to the propagation order (com > dac > def > trv > ill)"
Currently, we are checking only the interval part for comparison which defies the above statement.

But we also have this test in the ITF1788 suite,
`@test ==(DecoratedInterval(Interval(1.0, 2.0), def), DecoratedInterval(Interval(1.0, 2.0), trv))`
which is expecting a True answer(even though the decoration is different).

**Comment by dpsanders** [comment]
I understand that statement from the standard as referring only to decorations, not to decorated intervals.

I think we should follow the behaviour of the octave interval package here.

**Comment by krish8484** [comment]
In the test suite we have, 
`DecoratedInterval(2, 1) == nai() == true` 
but
`nai() == nai() == false`
Aren't they contradicting?
