### ISSUE TITLE
Inaccurate results due to rationalize(x)

### ISSUE THREAD

**Issue by krish8484** [JuliaIntervals/IntervalArithmetic.jl#395]
Currently, we are getting
```
julia> @interval("[1.0000000000000001, 1.0000000000000002]")
Interval(1.0, 1.0)
```
Expected Answer
```
Interval(1.0, 1.0000000000000002)
```
This is because of 
```
julia> rationalize(1.0000000000000002)
1//1
```
It should not be exactly 1//1

**Comment by dpsanders** [comment]
You can change the tolerance on `rationalize`, I believe.
Or we should switch back to parsing strings.

**Comment by dpsanders** [comment]
In this case we can just directly parse the strings.

**Comment by dpsanders** [comment]
Bump.

**Comment by OlivierHnt** [comment]
Fixed on master.
