### ISSUE TITLE
Plotting infinite IntervalBoxes

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#401]
Currently `Plots.jl` ignores objects that extend to infinity.
When plotting we should check for an infinity and replace it by a large finite number of the same sign.

**Comment by dpsanders** [comment]
e.g. replace `IntervalBox(a, b)` by `IntervalBox(a, b) ∩ (-1e10..1e10)))`

Note that this happens even with fixed `ylims`.

**Comment by OlivierHnt** [comment]
Resolved by #582.
