### ISSUE TITLE
Decoration of atan(y, x).

### ISSUE THREAD

**Issue by mizuno-gsinet** [JuliaIntervals/IntervalArithmetic.jl#406]
Why is this `dac` but not `def`? `atan(y, x)` is discontinuous on y = 0 ∧ x < 0, isn't it?

https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/d3a318c6356515ee2d2a0c47ab7af419dea106ea/test/ITF1788_tests/libieeep1788_tests_elem.jl#L4037

**Comment by mizuno-gsinet** [comment]
Oops! I'm sorry. In this case, the restriction is continuous, so it is `dac`. (I had a misunderstanding about the subspace topology of the domain.)

**Comment by dpsanders** [comment]
Sorry that I has not replied before.

We took this test from a large test set designed by other people. Do let us know if you think there is a problem. Thanks!
