### ISSUE TITLE
Doesn't work with GenericLinearAlgebra

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#407]
For eigenvalues of an interval matrix.

**Comment by lucaferranti** [comment]
I don't think that's a bug, it's a feature. It's very unlike that the algorithms implemented, even if the code compiled, would be robust and stable for intervals. Anyway, eigenvalues are on IntervalLinearAlgebra.jl roadmap, so I think this can be closed :)
