### ISSUE TITLE
Support for open sets?

### ISSUE THREAD

**Issue by kapple19** [JuliaIntervals/IntervalArithmetic.jl#422]
I would find this useful in my implementations. E.g. distinguishing between a variable hitting a boundary value as opposed to being strictly inside the range.

Any prospects on supporting open sets sometime?

**Comment by dpsanders** [comment]
In principle this would be possible (?), but it is not on the agenda. 

In most applications it seems to me that there is "probability 0" of exactly hitting the boundary.

**Comment by kapple19** [comment]
> In most applications it seems to me that there is "probability 0" of exactly hitting the boundary.

Also my thoughts. I just happen to have a model that would benefit greatly from having open sets, and so I opened this issue to see if anyone else has come across use cases too.

Plus, I know Invenia's Intervals.jl supports open sets, it's just too bad that I desire exclusive functionality from both packages.

Thanks!

**Comment by dpsanders** [comment]
In principle I think it should be possible to make a new package that uses IntervalArithmetic.jl but also calculates the open / closedness?

I did think about this at some point but I think there are tricky edge cases.

**Comment by mforets** [comment]
> In most applications it seems to me that there is "probability 0" of exactly hitting the boundary.

:+1:  I see a use case for the notion of open set for those applications that require exact arithmetic (rationals). Otherwise, one can generally work with complements for questions such as set membership. For instance,

```julia
using LazySets, IntervalArithmetic

# that's x >= 1
H = HalfSpace([-interval(1), interval(0)], -interval(1.0)) 

# and this is the (symbolic) complement of H
julia> Hc = Complement(H)
Complement{IntervalArithmetic.Interval{Float64},HalfSpace{IntervalArithmetic.Interval{Float64},Array{IntervalArithmetic.Interval{Float64},1}}}(HalfSpace{IntervalArithmetic.Interval{Float64},Array{IntervalArithmetic.Interval{Float64},1}}(IntervalArithmetic.Interval{Float64}[[-1, -1], [0, 0]], [-1, -1]))

julia> [interval(1), interval(2)] ∈ Hc
false

julia> [interval(1), interval(2)] ∈ H
true

julia> [interval(1) - 1e-10, interval(2)] ∈ Hc
true
```
