### ISSUE TITLE
Add methods for `sind` and etc.

### ISSUE THREAD

**Issue by goretkin** [JuliaIntervals/IntervalArithmetic.jl#423]
Currently it falls back to `sind(::Real)` defined in Base:

```julia
julia> sind(interval(0, 0))
ERROR: rem not defined for IntervalArithmetic.Interval{Float64}
```

**Comment by dpsanders** [comment]
This should be pretty easy: just divide (or multiply?) by interval pi?

**Comment by goretkin** [comment]
Ideally it would benefit from https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/421 to avoid the same issues.
