### ISSUE TITLE
Mince should return an iterator 

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#431]
For efficiency

**Comment by dpsanders** [comment]
I think it's just a question of replacing the array comprehension by a generator expression:

```jl
julia> function mince(x::Interval, n)
             nodes = range(x.lo, x.hi, length = n+1)
             return (Interval(nodes[i], nodes[i+1]) for i in 1:length(nodes)-1)
         end
```

**Comment by lbenet** [comment]
I've open #467, which improves performance (broadcasting!), but returns a vector...

**Comment by OlivierHnt** [comment]
Is this still a wanted feature?

**Comment by edtrelo** [comment]
@dpsanders what about using a new structure that relies on ranges? @lbenet and I have been discussing this issue and we think it would be useful to have an implementation of the `getindex` method, that proposed structure would enable us to achive such task.

**Comment by edtrelo** [comment]
`@btime mince($`
