### ISSUE TITLE
Display empty IntervalBox as ∅

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#432]
An empty `IntervalBox` should be displayed as `∅`, rather than `∅ × ∅`

**Comment by lucaferranti** [comment]
what about interval boxes in the form `IntervalBox(emptyinterval(), 1..2, emptyinterval())`, should those also be displayed as `∅`, since technically those are empty interval boxes too?

```
julia> a = IntervalBox(emptyinterval(), 1..2, emptyinterval())
∅ × [1, 2] × ∅

julia> isempty(a)
true
```

**Comment by dpsanders** [comment]
Yes they should also be displayed in the same way. Alternatively when an Interval box is created it should check if any element is empty and return an empty interval if so. I think performance was the reason for not doing this. The performance shoukd be checked
