### ISSUE TITLE
Extra allocations from multiplication (redefining functions in the REPL alleviates allocations)

### ISSUE THREAD

**Issue by OlivierHnt** [JuliaIntervals/IntervalArithmetic.jl#435]
This is a follow-up of [this](https://discourse.julialang.org/t/redefining-functions-in-the-repl-alleviates-large-allocations-mwe-with-intervalarithmetic-jl/53515) discussion in discourse.

Multiplication of intervals in functions defined inside a module leads to 6 extra allocations per `*`. Interestingly, redefining the function in the REPL fixes the issue.

Here is a MWE:

```julia
module MyModule
    foo(x) = x*x
    export foo
end

using .MyModule, IntervalArithmetic, BenchmarkTools

x = @interval(π);

@btime foo(Ref($x)[]);
# 137.597 ns (6 allocations: 96 bytes)

MyModule.foo(x) = x*x

@btime foo(Ref($x)[]);
# 59.040 ns (0 allocations: 0 bytes)
```

**Comment by OlivierHnt** [comment]
To add to this issue: the division operator `/` does not have this problem and `*` has the extra allocations only when multiplying two intervals.

<details>
  <summary>See the MWE</summary>
```Julia
module MyModule
    mymul(x, y) = x*y
    mydiv(x, y) = x/y
    export mymul, mydiv
end

using .MyModule, IntervalArithmetic, BenchmarkTools

x = @interval(π);

y = @interval(π);
@btime mymul($x, $y);
@btime mydiv($x, $y);

y = π;
@btime mymul($x, $y);
@btime mydiv($x, $y);
```
</details>

I am not familiar with the internal choices of the package, but could `*` be reworked in a similar style to `/`?

**Comment by Kolaru** [comment]
It is because somehow inlining of `foo` doesn't happen. If you explicitly `@inline` it (as it is done internally by IntervalArithmetic for `*`) the extra allocations are gone

```julia
julia> module CoolModule
           foo(x) = x*x
           @inline infoo(x) = x*x
           export foo, infoo
       end
Main.CoolModule

julia> using IntervalArithmetic

julia> using BenchmarkTools

julia> using .CoolModule

julia> x = @interval(π)
[3.14159, 3.1416]

julia> @btime foo(Ref($x)[])
  43.116 ns (6 allocations: 96 bytes)
[9.8696, 9.86961]

julia> @btime infoo(Ref($x)[])
  10.372 ns (0 allocations: 0 bytes)
[9.8696, 9.86961]
```

We have to specifically inline `*` and not `/` because the former has some annoying corner cases, leading to a more involved code the compiler may be reluctant to inline.

That being sayed the issue remains: it is not good to loose the inlining benefit in user defined modules.

**Comment by dpsanders** [comment]
Thanks for the detective work! 

We should probably just use `@inline` on all these functions.

**Comment by OlivierHnt** [comment]
As I mentioned on discourse, unfortunately the macro `@inline` does not always prevent the extra allocations.

Here is yet an other behaviour:

```Julia
module MyModule
    using IntervalArithmetic
    *(Interval(1), Interval(1)) # <- prevents extra allocations

    function foo(v)
        w = zero.(v)
        for i ∈ eachindex(w)
            _foo!(w, v, i)
        end
        return w
    end

    function _foo!(w, v, i)
        for j ∈ 1:i
            w[i] += v[i]*v[j]
        end
    end
   
    export foo
end

using .MyModule, IntervalArithmetic, BenchmarkTools

v = Interval.(rand(1_000));
@btime foo($v);
```

It is a convenient work around, however it does not seem to scale well with the project size. I tried it on a module which `include` multiple files and it does not work; for large projects, re-defining the functions remain the only way to prevent allocations as far as I know.

**Comment by OlivierHnt** [comment]
The following operation is very slow and may be related to this issue:

```
using IntervalArithmetic, BenchmarkTools

A = Interval.(rand(100, 100))

@btime $A * $A; # 184.122 ms (6000020 allocations: 91.71 MiB) 
```

It is becoming less and less easy to hack around this issue 😞.

I tried to look more into it (e.g. with some profiling)... Not much luck.

@Kolaru have you been able to investigate further?
Also I wonder if this problem also occurs with `TaylorModels.jl`.

**Comment by dpsanders** [comment]
You can also use `setrounding(Interval, :fast)` to use a faster method of directed rounding.

If you really need fast multiplication of interval matrices then you will need to implement Rump's method using rounding-mode changes and floating-point matrix multiplication (can't find the reference right now).

**Comment by OlivierHnt** [comment]
Thank you for your feedback. Are you referring to this paper [Fast interval matrix multiplication](https://link.springer.com/article/10.1007/s11075-011-9524-z)?

**Comment by lucaferranti** [comment]
You can find the documentation of different rounding modes [here](https://juliaintervals.github.io/pages/tutorials/tutorialArithmetic/#rounding_modes).

**Comment by OlivierHnt** [comment]
Thanks for the link.

I went through the five rounding modes:

```Julia
using IntervalArithmetic, BenchmarkTools

A = Interval.(rand(100, 100));

setrounding(Interval, :fast);
@btime $A*$A; # 69.620 ms (8 allocations: 156.66 KiB)

setrounding(Interval, :accurate);
@btime $A*$A; # 13.685 ms (8 allocations: 156.66 KiB)

setrounding(Interval, :tight);
@btime $A*$A; # 172.094 ms (6000020 allocations: 91.71 MiB)

setrounding(Interval, :slow);
@btime $A*$A; # 226.559 ms (8 allocations: 156.66 KiB)

setrounding(Interval, :none);
@btime $A*$A; # 8.206 ms (8 allocations: 156.66 KiB)

#-- trick to remove extra allocations observed when rounding set to :tight
@inline function Base.:*(a::Interval{T}, b::Interval{T}) where T<:Real
    (isempty(a) || isempty(b)) && return emptyinterval(T)

    (iszero(a) || iszero(b)) && return zero(Interval{T})

    (isfinite(a) && isfinite(b)) && return IntervalArithmetic.mult(*, a, b)

    return IntervalArithmetic.mult(IntervalArithmetic.checked_mult, a, b)
end
#---

setrounding(Interval, :tight);
@btime $A*$A; # 84.958 ms (8 allocations: 156.66 KiB)
```

The extra allocations are only observed when the rounding is set to `:tight`; perhaps you already knew this though :).

**Comment by dpsanders** [comment]
@olivierHnt: Have you tried inlining the functions inside the package?

**Comment by OlivierHnt** [comment]
Yes I did try it on a large project but it did not work.
Somehow, sometimes (e.g. for `setrounding(Interval, :tight)`), the inlining of `*` is lost.

Additionally, in the MWE @Kolaru provided with `@inline` there was no need to call `using IntervalArithmetic` inside the module. I gave a counter example on Discourse: on a slightly bigger module, it becomes necessary (cf. the following code).

<details><summary>Code</summary>

```Julia
using IntervalArithmetic, BenchmarkTools

v = Interval.(rand(1_000));

module M1    
    function M1_foo(v)
        w = zero.(v)
        for i ∈ eachindex(w)
            _foo!(w, v, i)
        end
        return w
    end

    @inline function _foo!(w, v, i)
        for j ∈ 1:i
            w[i] += v[i]*v[j]
        end
    end
   
    export M1_foo
end

using .M1
@btime M1_foo($v);

module M2
    using IntervalArithmetic
    
    function M2_foo(v)
        w = zero.(v)
        for i ∈ eachindex(w)
            _foo!(w, v, i)
        end
        return w
    end

    @inline function _foo!(w, v, i)
        for j ∈ 1:i
            w[i] += v[i]*v[j]
        end
    end
   
    export M2_foo
end

using .M2
@btime M2_foo($v);
```
</details>

Also, these sort of things happen:

```Julia
using IntervalArithmetic, BenchmarkTools

A = Interval.(rand(10, 10));

Interval(1)*Interval(1) # we perform `*` once before any computation

@btime $A*$A; # 85.819 μs (5 allocations: 1.98 KiB)
```

compared to

```Julia
using IntervalArithmetic, BenchmarkTools

A = Interval.(rand(10, 10));

A*A # some computation...

@btime $A*$A; # 191.300 μs (6017 allocations: 95.92 KiB)

Interval(1)*Interval(1) # this will no longer prevent the extra allocations

@btime $A*$A; # 191.681 μs (6017 allocations: 95.92 KiB)
```

If you give Julia the opportunity to compile just `*`, things seem fine. However, if we perform an other operation before, then Julia seems to get mixed up...

**Comment by dpsanders** [comment]
I meant: Did you try modifying the code in IntervalArithmetic.jl to explicitly inline all the relevant functions?

**Comment by OlivierHnt** [comment]
I see. No I did not try it; I'll give it a shot perhaps next week then.

**Comment by OlivierHnt** [comment]
Sorry for the late feedback. I use `@inline` in front of the following functions:

- https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/a3dc27f52939812742754e1df50a65c7608679c5/src/intervals/rounding.jl#L134-L135
- https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/a3dc27f52939812742754e1df50a65c7608679c5/src/intervals/rounding.jl#L175-L180
- https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/a3dc27f52939812742754e1df50a65c7608679c5/src/intervals/rounding.jl#L278

No luck.

**Comment by dpsanders** [comment]
@OlivierHnt: What about mult for example? And any other function involved in the multiplication.

**Comment by OlivierHnt** [comment]
Do you mean these? https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/a3dc27f52939812742754e1df50a65c7608679c5/src/intervals/arithmetic.jl#L110-L136

These functions were already preceded by the `@inline`macro so I did not change it. Am I missing something?

**Comment by dpsanders** [comment]
Sorry for the delay. Yes, that's what I meant.
In that case I don't know what's happening.

Maybe @lucaferranti can investigate.

**Comment by OlivierHnt** [comment]
I tested the [initial MWE](https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/435#issue-789164595) on Julia 1.8.0-rc3, it seems that the issue is resolved (and may be closed?). Could someone test this as well and confirm?

```Julia
julia> versioninfo()
Julia Version 1.8.0-rc3
Commit 33f19bcbd25 (2022-07-13 19:10 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores

julia> module MyModule
           foo(x) = x*x
           export foo
       end
Main.MyModule

julia> using .MyModule, IntervalArithmetic, BenchmarkTools

julia> x = @interval(π);

julia> @btime foo(Ref($x)[]);
  10.427 ns (0 allocations: 0 bytes)
```
