### ISSUE TITLE
Generalize IntervalBox split for non-uniform partitions

### ISSUE THREAD

**Issue by mforets** [JuliaIntervals/IntervalArithmetic.jl#444]
Currently, `mince` for interval boxes receives an integer `n` to divide the box n times along each dimension,

https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/b70940dabdbefd8eb4be32d7bde6df72174dd3f7/src/multidim/intervalbox.jl#L124

Sometimes it is useful to have a function that accepts a non-uniform partition, say `[2, 3]` to split the first dimension two times and the second dimension 3 times, obtaning 6 boxes. (This is what `split(::AbstractHyperrectangle, block::AbstractVector)` does.)

**Comment by dpsanders** [comment]
I'm not sure what you mean by this?

**Comment by mforets** [comment]
oops, description added :+1:

**Comment by dpsanders** [comment]
Ah, I see. Good idea!
