### ISSUE TITLE
Add isatomic function

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#46]
For checking if an interval is atomic, ie unable to be split further.

**Comment by lbenet** [comment]
How is this related to `isthin`? 

I guess that for exactly representable floating points it is equivalent, and it would return `true` for `@interval(0.1)`; `isthin( @interval(0.1) )` returns `false`.

**Comment by dpsanders** [comment]
Yes, exactly. An atomic interval is an interval that cannot be split up any more by bisection.

**Comment by dpsanders** [comment]
isatomic(x::Interval) = x.hi <= nextfloat(x.lo)

**Comment by lbenet** [comment]
LGTM. Can you submit a PR (with a couple of tests and docstrings) and merge it right away? :)

Note the following implication (which is probably ok):
```julia
julia> isatomic(x::Interval) = x.hi <= nextfloat(x.lo)
isatomic (generic function with 1 method)

julia> isatomic(emptyinterval())
true
```

**Comment by dpsanders** [comment]
PR: #58
