### ISSUE TITLE
`eltype` should return the full `Interval` type (?)

### ISSUE THREAD

**Issue by jonniedie** [JuliaIntervals/IntervalArithmetic.jl#487]
It seems to be that the convention for `eltype` of a `<:Number`s is to return the type itself, rather than any inner element type. For example:
```julia
julia> eltype(1//2)
Rational{Int64}

julia> eltype(1+im)
Complex{Int64}
```
`Interval`s, on the other hand, give the `eltype` as the inner element type.
```julia
julia> eltype(1..2)
Float64
```
This causes some issues with packages ([Polynomials.jl, for example](https://github.com/JuliaMath/Polynomials.jl/blob/305fcef4024d7ae6f4f438ac1381ba021ef8c890/src/polynomials/standard-basis.jl#L438)) that assume this convention.

**Comment by dpsanders** [comment]
I agree with you. I think there was a previous issue (or several) about this.

**Comment by lucaferranti** [comment]
yes this was discussed also in #397
