### ISSUE TITLE
[ANN] Round table in upcoming workshop

### ISSUE THREAD

**Issue by mforets** [JuliaIntervals/IntervalArithmetic.jl#498]
FYI: As it has been announced on different platforms (JuliaLang's zulip, slack, [discourse](https://discourse.julialang.org/t/juliareach-juliaintervals-days-3/71829)), JuliaReach and JuliaIntervals maintainers joined efforts to make a workshop in December. The workshop will host a round table with particular emphasis to IntervalArithmetic.jl roadmap towards version 1.0.

The event is free, but registration is required as we will share connection details by DM: https://juliareach.github.io/juliareach-days-3/

**Comment by lbenet** [comment]
Closing, since it passed...
