### ISSUE TITLE
define `inf, sup` etc. for non-intervals

### ISSUE THREAD

**Issue by lucaferranti** [JuliaIntervals/IntervalArithmetic.jl#510]
What do you think, would it make sense to define, e.g.

```julia
mid(x::Number) = x
inf(x::Number) = x
sup(x::Number) = x
rad(x::Number) = zero(x)
```

etc.

I think they could be useful to write generic code that works both for intervals and non-intervals

**Comment by lbenet** [comment]
I agree with you that those methods may be useful and certainly it doesn't hurt to have them around.
