### ISSUE TITLE
Extend inclusion check for interval and interval box

### ISSUE THREAD

**Issue by mforets** [JuliaIntervals/IntervalArithmetic.jl#519]
```julia
julia> (0 .. 1) ⊆ IntervalBox(0 .. 1, 1)
ERROR: ArgumentError: [0, 1] ∈ [0, 1]¹ is not defined
Stacktrace:
 [1] in(X::IntervalArithmetic.Interval{Float64}, Y::IntervalBox{1, Float64})
   @ IntervalArithmetic ~/.julia/packages/IntervalArithmetic/997vH/src/multidim/intervalbox.jl:82
 [2] issubset(l::IntervalArithmetic.Interval{Float64}, r::IntervalBox{1, Float64})
   @ Base ./abstractset.jl:293
 [3] top-level scope
   @ REPL[39]:1
```

**Comment by lucaferranti** [comment]
what should `(0 .. 1) ⊆ IntervalBox(0 .. 1, 2)` return? Since `IntervalBox` uses `N` (the dimension) as parameter type, we could define

```julia
⊆(a::Interval, b::IntervalBox{1}) = a ⊆ first(b)
``` 

do you need this somewhere in JuliaReach?

**Comment by mforets** [comment]
The solution you propose sounds good to me 👍 
(No need to implement it with `IntervalBox{N}` for `N` higher than one as the default MethodError is usually fine).

> do you need this somewhere in JuliaReach?

Yes, this is to avoid special casing inputs which can be 1-dim or mult-dim intervals.
