### ISSUE TITLE
Allow date intervals

### ISSUE THREAD

**Issue by jariji** [JuliaIntervals/IntervalArithmetic.jl#526]
I want to make an interval with dates but it doesn't work. Is it necessary to restrict the type?

```jl
julia> interval(today()-Day(1), today())
ERROR: MethodError: no method matching interval(::Date, ::Date)
```

**Comment by lbenet** [comment]
The problem boils down to the fact that `Date` is not subtype of `Real`.

A possible way around is to use [Julian days](https://en.wikipedia.org/wiki/Julian_day):
```julia
julia> datetime2julian( now() )
2.4597270494904863e6

julia> Interval(ans-1, ans)
[2.45972e+06, 2.45973e+06]
```

**Comment by jariji** [comment]
I can convert dates into numbers as a workaround but it does seem like an unnecessary complication. Could the `Real` restriction be removed, so I could use `Date` directly?

**Comment by Kolaru** [comment]
I think https://github.com/invenia/Intervals.jl may be doing what you want.

Interval arithmetic, on the other hand, really refers to doing floating point arithmetic with interval. I don't think there is a straightforward extension of this to dates.

**Comment by jariji** [comment]
I see, thanks.
