### ISSUE TITLE
Avoid use of `rationalize` in conversion?

### ISSUE THREAD

**Issue by lbenet** [JuliaIntervals/IntervalArithmetic.jl#53]
See #51

**Comment by dpsanders** [comment]
Yes, I think we should just use prevfloat and nextfloat for convert...

**Comment by lbenet** [comment]
I'll test that idea...

**Comment by dpsanders** [comment]
Basically 
```
convert(Interval, x::Float64) = x..x
```
with the definition of `..` in #37 .

**Comment by dpsanders** [comment]
Resolved in the negative (i.e. Keeping rationalise when possible) on #51.
