### ISSUE TITLE
Power of negative numbers is broken for non-rational exponents

### ISSUE THREAD

**Issue by petvana** [JuliaIntervals/IntervalArithmetic.jl#536]
Just some examples (Julia v1.7.3 + IntervalArithmetic v0.20.6):
``` julia
julia> using IntervalArithmetic

julia> (-1.0..1.0)^0.9
[0, 1]

julia> (-2..(-1))^0.9
∅

julia> (-2..(-1))^(0.9..0.9)
∅

julia> (-2..(-1))^3
[-8, -1]
```

**Comment by lucaferranti** [comment]
that seems correct to me. The (real) function $x^y$ where $y$ is a real number is only defined for positive $x$. Compare to normal julia behavior

```
julia> (-2.0) ^ 0.9
ERROR: DomainError with -2.0:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar.
Stacktrace:
 [1] throw_exp_domainerror(x::Float64)
   @ Base.Math ./math.jl:37
 [2] ^(x::Float64, y::Float64)
   @ Base.Math ./math.jl:909
 [3] top-level scope
   @ REPL[17]:1
```

hence when the base interval is fully negative the result is an empty interval.

For the first case $[-1, 1]^{0.9}$, it follows the  behavior recommended by the IEEE standard, that is when the interval is partially outside the domain, evaluate the function only on the part of the interval in the domain

**Comment by petvana** [comment]
I'm sorry, I'm stupid ... I was missing brackets and it makes no sense of course. (`-1.5^0.9`)

**Comment by lucaferranti** [comment]
no problems I always forget those brackets too :)
