### ISSUE TITLE
Provide tool for checking if a function plays well with intervals

### ISSUE THREAD

**Issue by Kolaru** [JuliaIntervals/IntervalArithmetic.jl#537]
There recently have been [some discussions](https://discourse.julialang.org/t/discussion-on-why-i-no-longer-recommend-julia-by-yuri-vishnevsky/81151) about what can be done in Julia to prevent composing various package in a way that leads to silent error or nonsensical result. A possible solution is better test infrastructure.

I thought about what it could mean for IA since we had quite serious silent bugs caused by IA being used with boolean operations.

It could be interesting to provide a function like
```
plays_well_with_IA(func, args...)
```

where `args` contains some interval arguments. Then `func(args...)` is computed as well as the values of `func` for a bunch of point inside the intervals (maybe the bounds and random points inside) and the values are checked to fall inside `func(args...)`.

This would allow users to easily have a sanity check to see if everything seems fine and could be used in the package tests as well.

**Comment by lbenet** [comment]
Fully agree with the idea! Incidentally, the same function could be used inside our own tests to check consistency. In TaylorModels I implemented something like that, though certainly not so user friendly, which includes calculations using extended precision.

**Comment by OlivierHnt** [comment]
What is the status of this issue? I have been thinking about this from time to time, but it is maybe too broad to be truly actionable.

Maybe this issue is even a little outdated? Do the "NG" flag, the `@exact` macro and the removal of most comparison operations from Base (e.g. `<`) address this issue? Or do you have other ideas you would like to explore?
