### ISSUE TITLE
IntervalArithmetic.jl testing errors / broken found. 

### ISSUE THREAD

**Issue by iajzenszmi** [JuliaIntervals/IntervalArithmetic.jl#540]
@v1.7) pkg> add IntervalArithmetic
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
   Installed SetRounding ───────── v0.2.1
   Installed FastRounding ──────── v0.3.1
   Installed CRlibm_jll ────────── v1.0.1+0
   Installed RoundingEmulator ──── v0.2.1
   Installed ErrorfreeArithmetic ─ v0.5.2
   Installed CRlibm ────────────── v1.0.1
   Installed IntervalArithmetic ── v0.20.6
  Downloaded artifact: CRlibm
    Updating `~/.julia/environments/v1.7/Project.toml`
  [d1acc4aa] + IntervalArithmetic v0.20.6
    Updating `~/.julia/environments/v1.7/Manifest.toml`
  [96374032] + CRlibm v1.0.1
  [90fa49ef] + ErrorfreeArithmetic v0.5.2
  [fa42c844] + FastRounding v0.3.1
  [d1acc4aa] + IntervalArithmetic v0.20.6
  [5eaf0fd0] + RoundingEmulator v0.2.1
  [3cc68bcd] + SetRounding v0.2.1
  [4e9b3aee] + CRlibm_jll v1.0.1+0
Precompiling project...
  7 dependencies successfully precompiled in 30 seconds (417 already precompiled, 1 skipped during auto due to previous errors)

(@v1.7) pkg> test IntervalArithmetic
     Testing IntervalArithmetic
┌ Warning: Could not use exact versions of packages in manifest, re-resolving
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:1488
      Status `/tmp/jl_UGQbQJ/Project.toml`
  [96374032] CRlibm v1.0.1
  [fa42c844] FastRounding v0.3.1
  [d1acc4aa] IntervalArithmetic v0.20.6
  [15111844] IntervalContractors v0.4.7
  [f27b6e38] Polynomials v0.7.0
  [3cdcf5f2] RecipesBase v1.2.1
  [5eaf0fd0] RoundingEmulator v0.2.1
  [3cc68bcd] SetRounding v0.2.1
  [90137ffa] StaticArrays v1.5.2
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [9a3f8284] Random `@stdlib/Random`
  [8dfed614] Test `@stdlib/Test`
      Status `/tmp/jl_UGQbQJ/Manifest.toml`
  [96374032] CRlibm v1.0.1
  [34da2185] Compat v3.45.0
  [90fa49ef] ErrorfreeArithmetic v0.5.2
  [e2ba6199] ExprTools v0.1.8
  [fa42c844] FastRounding v0.3.1
  [842dd82b] InlineStrings v1.1.4
  [d1acc4aa] IntervalArithmetic v0.20.6
  [15111844] IntervalContractors v0.4.7
  [d8418881] Intervals v1.8.0
  [692b3bcd] JLLWrappers v1.4.1
  [78c3b35d] Mocking v0.7.3
  [69de0a69] Parsers v2.3.2
  [f27b6e38] Polynomials v0.7.0
  [21216c6a] Preferences v1.3.0
  [3cdcf5f2] RecipesBase v1.2.1
  [5eaf0fd0] RoundingEmulator v0.2.1
  [6c6a2e73] Scratch v1.1.1
  [3cc68bcd] SetRounding v0.2.1
  [90137ffa] StaticArrays v1.5.2
  [1e83bf80] StaticArraysCore v1.0.1
  [f269a46b] TimeZones v1.9.0
  [4e9b3aee] CRlibm_jll v1.0.1+0
  [0dad84c5] ArgTools `@stdlib/ArgTools`
  [56f22d72] Artifacts `@stdlib/Artifacts`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [ade2ca70] Dates `@stdlib/Dates`
  [8bb1440f] DelimitedFiles `@stdlib/DelimitedFiles`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [f43a241f] Downloads `@stdlib/Downloads`
  [7b1f6079] FileWatching `@stdlib/FileWatching`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [4af54fe1] LazyArtifacts `@stdlib/LazyArtifacts`
  [b27032c2] LibCURL `@stdlib/LibCURL`
  [76f85450] LibGit2 `@stdlib/LibGit2`
  [8f399da3] Libdl `@stdlib/Libdl`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [a63ad114] Mmap `@stdlib/Mmap`
  [ca575930] NetworkOptions `@stdlib/NetworkOptions`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [3fa0cd96] REPL `@stdlib/REPL`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA `@stdlib/SHA`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [1a1011a3] SharedArrays `@stdlib/SharedArrays`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [10745b16] Statistics `@stdlib/Statistics`
  [fa267f1f] TOML `@stdlib/TOML`
  [a4e569a6] Tar `@stdlib/Tar`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
  [4ec0a83e] Unicode `@stdlib/Unicode`
  [e66e0078] CompilerSupportLibraries_jll `@stdlib/CompilerSupportLibraries_jll`
  [deac9b47] LibCURL_jll `@stdlib/LibCURL_jll`
  [29816b5a] LibSSH2_jll `@stdlib/LibSSH2_jll`
  [c8ffd9c3] MbedTLS_jll `@stdlib/MbedTLS_jll`
  [14a3606d] MozillaCACerts_jll `@stdlib/MozillaCACerts_jll`
  [4536629a] OpenBLAS_jll `@stdlib/OpenBLAS_jll`
  [83775a58] Zlib_jll `@stdlib/Zlib_jll`
  [8e850b90] libblastrampoline_jll `@stdlib/libblastrampoline_jll`
  [8e850ede] nghttp2_jll `@stdlib/nghttp2_jll`
  [3f19e933] p7zip_jll `@stdlib/p7zip_jll`
Precompiling project...
  5 dependencies successfully precompiled in 57 seconds (23 already precompiled)
     Testing Running tests...
Test Summary:          | Pass  Broken  Total
Constructing intervals |  120       1    121
Test Summary: | Pass  Broken  Total
Big intervals |    6       1      7
Test Summary:     | Pass  Total
Complex intervals |    2      2
Test Summary:   | Pass  Total
Typed intervals |    9      9
Test Summary: | Pass  Total
.. tests      |   17     17
Test Summary: | Pass  Total
± tests       |    5      5
Test Summary:                       | Pass  Total
Conversion to interval of same type |    2      2
Test Summary:                                   | Pass  Total
Conversions between different types of interval |    2      2
Test Summary:          | Pass  Total
Conversion to Interval |    3      3
Test Summary:           | Pass  Total
Interval{T} constructor |    4      4
Test Summary:               | Pass  Total
Disallow NaN in an interval |    6      6
Test Summary:    | Pass  Total
Interval strings |    4      4
Test Summary: | Pass  Total
setdiff tests |    6      6
Test Summary:            | Pass  Total
Interval{T}(x::Interval) |    2      2
Test Summary:         | Pass  Total
@interval with fields |    1      1
Test Summary:                        | Pass  Total
@interval with user-defined function |    1      1
Test Summary:   | Pass  Total
a..b with a > b |    2      2
Test Summary:        | Pass  Total
Hashing of Intervals |    8      8
Test Summary:  | Pass  Total
force_interval |    6      6
Test Summary: | Pass  Total
Zero interval |    2      2
Test Summary:     | Pass  Total
Consistency tests |  250    250
Test Summary:     | Pass  Total
brodcasting tests |   81     81
Test Summary: | Pass  Total
Numeric tests |   35     35
Test Summary:             | Pass  Total
Arithmetic with constants |    5      5
Test Summary: | Pass  Total
Power tests   |   41     41
Test Summary:     | Pass  Total
Exp and log tests |   20     20
Test Summary:    | Pass  Total
Comparison tests |    8      8
Test Summary:  | Pass  Total
Rational tests |    8      8
Test Summary:    | Pass  Total
Floor etc. tests |   53     53
Test Summary: | Pass  Total
Fast power    |   37     37
Test Summary:         | Pass  Total
Mince for `Interval`s |    6      6
Test Summary: | Pass  Total
nthroot test  |   36     36
Test Summary: | Pass  Total
sin           |   14     14
Test Summary: | Pass  Total
cos           |   12     12
Test Summary: | Pass  Total
sinpi         |    5      5
Test Summary: | Pass  Total
cospi         |    5      5
Test Summary: | Pass  Total
tan           |   12     12
Test Summary: | Pass  Total
Inverse trig  |   15     15
Test Summary: | Pass  Total
atan          |   55     55
Test Summary: | Pass  Total
Trig          |    4      4
Test Summary:             | Pass  Total
Trig with large arguments |    7      7
Test Summary: | Pass  Total
Hyperb tests  |   48     48
Test Summary:                 | Pass  Total
Tests with rational intervals |    3      3
Test Summary:               | Pass  Total
Rounding rational intervals |    1      1
Test Summary:              | Pass  Total
Tests with float intervals |    4      4
Test Summary:                  | Pass  Total
Testing functions of intervals |    2      2
Test Summary:       | Pass  Total
Testing conversions |    2      2
Test Summary:                       | Pass  Total
Linear algebra with intervals tests |    2      2
Test Summary:       | Pass  Total
Interval loop tests |   12     12
Test Summary: | Pass  Total
Pi tests      |    7      7
Test Summary:            | Pass  Total
Parse string to Interval |   31     31
Test Summary:                     | Pass  Total
Parse string to DecoratedInterval |   20     20
Test Summary:                                  | Pass  Total
Tight, slow rounding by changing rounding mode |    2      2
Test Summary:                                         | Pass  Total
Accurate, fast rounding using prevfloat and nextfloat |    2      2
Test Summary: | Pass  Total
No rounding   |    3      3
Test Summary:                              | Pass  Total
Tight, fast rounding using FastRounding.jl |    2      2
Test Summary:                            | Pass  Total
Tight rounding using RoundingEmulator.jl |    6      6
Test Summary:     | Pass  Total
`bisect` function |   14     14
Test Summary:               | Pass  Total
Complex interval operations |   16     16
Test Summary:     | Pass  Total
Complex functions |    8      8
Test Summary:  | Pass  Total
Complex powers |    4      4
Test Summary: | Pass  Total
abs2 and abs  |    4      4
Test Summary:  | Pass  Total
real functions |    3      3
Test Summary:           | Pass  Total
DecoratedInterval tests |   37     37
Test Summary:                       | Pass  Total
Convert string to DecoratedInterval |    2      2
Test Summary: | Pass  Total
rand tests    |  330    330
Test Summary:   | Pass  Total
setformat tests |   58     58
Test Summary: | Pass  Total
showfull      |   12     12
Test Summary: | Pass  Total
@format tests |    3      3
Test Summary:       | Pass  Total
Operations on boxes |  144    144
Test Summary:      | Pass  Total
Functions on boxes |    5      5
Test Summary:           | Pass  Total
setdiff for IntervalBox |   10     10
Test Summary:                | Pass  Total
mid, diam, × for IntervalBox |   21     21
Test Summary:                               | Pass  Total
Constructing multidimensional IntervalBoxes |   16     16
Test Summary:         | Pass  Total
getindex and setindex |    5      5
Test Summary: | Pass  Total
Iteration     |    2      2
Test Summary: | Pass  Total
Broadcasting  |   23     23
Test Summary: | Pass  Total
∈             |    6      6
Test Summary:              | Pass  Total
Multiplication by a matrix |    2      2
Test Summary:                      | Pass  Total
Mince and hull for `IntervalBox`es |   18     18
Test Summary:            | Pass  Total
Special box constructors |    3      3
Test Summary:      | Pass  Total
minimal.atan2_test |   38     38
Test Summary:       | Pass  Total
cxsc.intervaladdsub |    6      6
Test Summary:       | Pass  Total
cxsc.intervalmuldiv |   31     31
Test Summary:       | Pass  Total
cxsc.intervalsetops |   24     24
Test Summary:          | Pass  Total
cxsc.intervalmixsetops |   12     12
Test Summary:        | Pass  Total
cxsc.scalarmixsetops |    6      6
Test Summary:           | Pass  Total
cxsc.intervalsetcompops |   34     34
Test Summary:                 | Pass  Total
cxsc.intervalscalarsetcompops |   35     35
Test Summary:        | Pass  Total
cxsc.intervalstdfunc |   12     12
Test Summary: | Pass  Total
FI_LIB.addii  |   19     19
Test Summary: | Pass  Total
FI_LIB.subii  |   19     19
Test Summary: | Pass  Total
FI_LIB.mulii  |   46     46
Test Summary: | Pass  Total
FI_LIB.divii  |   21     21
Test Summary:          | Pass  Broken  Total
FI_LIB.unary_functions |  708      50    758
Test Summary: | Pass  Total
IEEE1788.a    |    1      1
Test Summary: | Pass  Total
IEEE1788.b    |    4      4
Test Summary: | Pass  Total
IEEE1788.c    |   11     11
Test Summary: | Pass  Total
IEEE1788.d    |    3      3
Test Summary: | Pass  Total
IEEE1788.e    |    1      1
Test Summary: | Pass  Total
IEEE1788.e    |   18     18
Test Summary: | Pass  Total
IEEE1788.f    |    5      5
┌ Warning: Invalid input, empty interval is returned
└ @ IntervalArithmetic ~/.julia/packages/IntervalArithmetic/LgwfS/src/intervals/intervals.jl:106
Test Summary: | Pass  Broken  Total
exceptions    |    1       3      4
Test Summary:         | Pass  Total
minimal_is_empty_test |   14     14
Test Summary:             | Pass  Total
minimal_is_empty_dec_test |   15     15
Test Summary:          | Pass  Total
minimal_is_entire_test |   14     14
Test Summary:              | Pass  Total
minimal_is_entire_dec_test |   17     17
Test Summary:           | Pass  Total
minimal_is_nai_dec_test |   16     16
Test Summary:      | Pass  Total
minimal_equal_test |   15     15
Test Summary:          | Pass  Total
minimal_equal_dec_test |   19     19
Test Summary:       | Pass  Total
minimal_subset_test |   27     27
Test Summary:           | Pass  Total
minimal_subset_dec_test |   29     29
Test Summary:     | Pass  Total
minimal_less_test |   26     26
Test Summary:         | Pass  Total
minimal_less_dec_test |   30     30
Test Summary:         | Pass  Total
minimal_precedes_test |   21     21
Test Summary:             | Pass  Total
minimal_precedes_dec_test |   25     25
Test Summary:         | Pass  Total
minimal_interior_test |   16     16
Test Summary:             | Pass  Total
minimal_interior_dec_test |   20     20
Test Summary:              | Pass  Total
minimal_strictly_less_test |   14     14
Test Summary:                  | Pass  Total
minimal_strictly_less_dec_test |   18     18
Test Summary:                  | Pass  Total
minimal_strictly_precedes_test |   14     14
Test Summary:                      | Pass  Total
minimal_strictly_precedes_dec_test |   18     18
Test Summary:         | Pass  Total
minimal_disjoint_test |   10     10
Test Summary:             | Pass  Total
minimal_disjoint_dec_test |   14     14
Test Summary:            | Pass  Total
minimal_cancel_plus_test |   58     58
Test Summary:                | Pass  Total
minimal_cancel_plus_dec_test |   58     58
Test Summary:             | Pass  Total
minimal_cancel_minus_test |   63     63
Test Summary:                 | Pass  Total
minimal_cancel_minus_dec_test |   63     63
┌ Warning: Invalid input, empty interval is returned
└ @ IntervalArithmetic ~/.julia/packages/IntervalArithmetic/LgwfS/src/intervals/intervals.jl:106
┌ Warning: Invalid input, empty interval is returned
└ @ IntervalArithmetic ~/.julia/packages/IntervalArithmetic/LgwfS/src/intervals/intervals.jl:106
┌ Warning: Invalid input, empty interval is returned
└ @ IntervalArithmetic ~/.julia/packages/IntervalArithmetic/LgwfS/src/intervals/intervals.jl:106
┌ Warning: Invalid input, empty interval is returned
└ @ IntervalArithmetic ~/.julia/packages/IntervalArithmetic/LgwfS/src/intervals/intervals.jl:106
Test Summary:                 | Pass  Total
minimal_nums_to_interval_test |    8      8
Test Summary:                           | Pass  Total
minimal_nums_to_decorated_interval_test |    8      8
Test Summary:                 | Pass  Broken  Total
minimal_text_to_interval_test |   38      30     68
Test Summary:                           | Pass  Broken  Total
minimal_text_to_decorated_interval_test |   36      35     71
Test Summary:              | Pass  Broken  Total
minimal_interval_part_test |   13       1     14
Test Summary:        | Pass  Total
minimal_new_dec_test |   13     13
Test Summary:        | Pass  Broken  Total
minimal_set_dec_test |   16       6     22
Test Summary:                | Pass  Total
minimal_decoration_part_test |    6      6
Test Summary:    | Pass  Total
minimal_pos_test |   11     11
Test Summary:        | Pass  Total
minimal_pos_dec_test |    4      4
Test Summary:    | Pass  Total
minimal_neg_test |   11     11
Test Summary:        | Pass  Total
minimal_neg_dec_test |    4      4
Test Summary:    | Pass  Total
minimal_add_test |   31     31
Test Summary:        | Pass  Total
minimal_add_dec_test |    6      6
Test Summary:    | Pass  Total
minimal_sub_test |   31     31
Test Summary:        | Pass  Total
minimal_sub_dec_test |    6      6
Test Summary:    | Pass  Total
minimal_mul_test |  116    116
Test Summary:        | Pass  Total
minimal_mul_dec_test |    6      6
Test Summary:    | Pass  Total
minimal_div_test |  341    341
Test Summary:        | Pass  Total
minimal_div_dec_test |    6      6
Test Summary:      | Pass  Total
minimal_recip_test |   18     18
Test Summary:          | Pass  Total
minimal_recip_dec_test |    8      8
Test Summary:    | Pass  Total
minimal_sqr_test |   12     12
Test Summary:        | Pass  Total
minimal_sqr_dec_test |    4      4
Test Summary:     | Pass  Total
minimal_sqrt_test |   13     13
Test Summary:         | Pass  Total
minimal_sqrt_dec_test |    4      4
Test Summary:    | Pass  Total
minimal_fma_test |  564    564
Test Summary:        | Pass  Total
minimal_fma_dec_test |    3      3
Test Summary:     | Pass  Total
minimal_pown_test |  163    163
Test Summary:         | Pass  Total
minimal_pown_dec_test |   11     11
Test Summary:    | Pass  Total
minimal_pow_test | 1344   1344
Test Summary:        | Pass  Total
minimal_pow_dec_test |   84     84
Test Summary:    | Pass  Total
minimal_exp_test |   19     19
Test Summary:        | Pass  Total
minimal_exp_dec_test |    2      2
Test Summary:     | Pass  Total
minimal_exp2_test |   18     18
Test Summary:         | Pass  Total
minimal_exp2_dec_test |    2      2
Test Summary:      | Pass  Total
minimal_exp10_test |   19     19
Test Summary:          | Pass  Total
minimal_exp10_dec_test |    2      2
Test Summary:    | Pass  Total
minimal_log_test |   21     21
Test Summary:        | Pass  Total
minimal_log_dec_test |    3      3
Test Summary:     | Pass  Total
minimal_log2_test |   19     19
Test Summary:         | Pass  Total
minimal_log2_dec_test |    4      4
Test Summary:      | Pass  Total
minimal_log10_test |   20     20
Test Summary:          | Pass  Total
minimal_log10_dec_test |    2      2
Test Summary:    | Pass  Total
minimal_sin_test |   52     52
Test Summary:        | Pass  Total
minimal_sin_dec_test |    3      3
Test Summary:    | Pass  Total
minimal_cos_test |   52     52
Test Summary:        | Pass  Total
minimal_cos_dec_test |    3      3
Test Summary:    | Pass  Total
minimal_tan_test |   33     33
Test Summary:        | Pass  Total
minimal_tan_dec_test |   33     33
Test Summary:     | Pass  Total
minimal_asin_test |   18     18
Test Summary:         | Pass  Total
minimal_asin_dec_test |    5      5
Test Summary:     | Pass  Total
minimal_acos_test |   18     18
Test Summary:         | Pass  Total
minimal_acos_dec_test |    5      5
Test Summary:     | Pass  Total
minimal_atan_test |   10     10
Test Summary:         | Pass  Total
minimal_atan_dec_test |    5      5
Test Summary:      | Pass  Total
minimal_atan2_test |  169    169
Test Summary:          | Pass  Total
minimal_atan2_dec_test |  169    169
Test Summary:     | Pass  Total
minimal_sinh_test |   11     11
Test Summary:         | Pass  Total
minimal_sinh_dec_test |    5      5
Test Summary:     | Pass  Total
minimal_cosh_test |   11     11
Test Summary:         | Pass  Total
minimal_cosh_dec_test |    5      5
Test Summary:     | Pass  Total
minimal_tanh_test |   11     11
Test Summary:         | Pass  Total
minimal_tanh_dec_test |    5      5
Test Summary:      | Pass  Total
minimal_asinh_test |   11     11
Test Summary:          | Pass  Total
minimal_asinh_dec_test |    5      5
Test Summary:      | Pass  Total
minimal_acosh_test |   11     11
Test Summary:          | Pass  Total
minimal_acosh_dec_test |    8      8
Test Summary:      | Pass  Total
minimal_atanh_test |   15     15
Test Summary:          | Pass  Total
minimal_atanh_dec_test |    9      9
Test Summary:     | Pass  Total
minimal_sign_test |   11     11
Test Summary:         | Pass  Total
minimal_sign_dec_test |    7      7
Test Summary:     | Pass  Total
minimal_ceil_test |   15     15
Test Summary:         | Pass  Total
minimal_ceil_dec_test |   14     14
Test Summary:      | Pass  Total
minimal_floor_test |   13     13
Test Summary:          | Pass  Total
minimal_floor_dec_test |   12     12
Test Summary:      | Pass  Total
minimal_trunc_test |   13     13
Test Summary:          | Pass  Total
minimal_trunc_dec_test |   12     12
Test Summary:                   | Pass  Total
minimal_round_ties_to_even_test |   18     18
Test Summary:                       | Pass  Total
minimal_round_ties_to_even_dec_test |    6      6
Test Summary:                   | Pass  Total
minimal_round_ties_to_away_test |   18     18
Test Summary:                       | Pass  Total
minimal_round_ties_to_away_dec_test |    7      7
Test Summary:    | Pass  Total
minimal_abs_test |   12     12
Test Summary:        | Pass  Total
minimal_abs_dec_test |    8      8
Test Summary:    | Pass  Total
minimal_min_test |   15     15
Test Summary:        | Pass  Total
minimal_min_dec_test |    4      4
Test Summary:    | Pass  Total
minimal_max_test |   15     15
Test Summary:        | Pass  Total
minimal_max_dec_test |    4      4
Test Summary:    | Pass  Total
minimal_inf_test |   14     14
Test Summary:        | Pass  Total
minimal_inf_dec_test |   15     15
Test Summary:    | Pass  Total
minimal_sup_test |   14     14
Test Summary:        | Pass  Total
minimal_sup_dec_test |   15     15
Test Summary:    | Pass  Broken  Total
minimal_mid_test |   11       1     12
Test Summary:        | Pass  Broken  Total
minimal_mid_dec_test |   12       1     13
Test Summary:    | Pass  Total
minimal_rad_test |    9      9
Test Summary:        | Pass  Total
minimal_rad_dec_test |   10     10
Test Summary:        | Pass  Broken  Total
minimal_mid_rad_test |   11       1     12
Test Summary:            | Pass  Broken  Total
minimal_mid_rad_dec_test |   12       1     13
Test Summary:    | Pass  Total
minimal_wid_test |    8      8
Test Summary:        | Pass  Total
minimal_wid_dec_test |    9      9
Test Summary:    | Pass  Total
minimal_mag_test |    8      8
Test Summary:        | Pass  Total
minimal_mag_dec_test |    9      9
Test Summary:    | Pass  Total
minimal_mig_test |   11     11
Test Summary:        | Pass  Total
minimal_mig_dec_test |   12     12
Test Summary:        | Broken  Total
minimal_overlap_test |     48     48
Test Summary:            | Broken  Total
minimal_overlap_dec_test |     29     29
Test Summary:                   | Pass  Total
minimal_is_common_interval_test |   12     12
Test Summary:                       | Pass  Total
minimal_is_common_interval_dec_test |   21     21
Test Summary:             | Pass  Total
minimal_is_singleton_test |   15     15
Test Summary:                 | Pass  Total
minimal_is_singleton_dec_test |   16     16
Test Summary:          | Pass  Total
minimal_is_member_test |   35     35
Test Summary:              | Pass  Total
minimal_is_member_dec_test |   40     40
Test Summary:    | Pass  Total
minimal_sum_test |    3      3
Test Summary:        | Pass  Total
minimal_sum_abs_test |    3      3
Test Summary:        | Pass  Total
minimal_sum_sqr_test |    3      3
Test Summary:    | Pass  Broken  Total
minimal_dot_test |    5       1      6
Test Summary:             | Pass  Total
minimal_intersection_test |    5      5
Test Summary:                 | Pass  Total
minimal_intersection_dec_test |    5      5
Test Summary:            | Pass  Total
minimal_convex_hull_test |    5      5
Test Summary:                | Pass  Total
minimal_convex_hull_dec_test |    5      5
Test Summary: | Pass  Total
mpfi_abs      |   12     12
Test Summary: | Pass  Total
mpfi_acos     |    8      8
Test Summary: | Pass  Total
mpfi_acosh    |    5      5
Test Summary: | Pass  Total
mpfi_add      |   19     19
Test Summary: | Pass  Total
mpfi_add_d    |   32     32
Test Summary: | Pass  Total
mpfi_asin     |    8      8
Test Summary: | Pass  Total
mpfi_asinh    |   19     19
Test Summary: | Pass  Total
mpfi_atan     |   19     19
Test Summary: | Pass  Total
mpfi_atan2    |   18     18
Test Summary: | Pass  Total
mpfi_atanh    |    9      9
Test Summary:  | Pass  Total
mpfi_bounded_p |   16     16
Test Summary: | Pass  Total
mpfi_cbrt     |   10     10
Test Summary: | Pass  Total
mpfi_cos      |   46     46
Test Summary: | Pass  Total
mpfi_cosh     |   14     14
Test Summary: | Pass  Total
mpfi_cot      |   19     19
Test Summary: | Pass  Total
mpfi_coth     |   16     16
Test Summary: | Pass  Total
mpfi_csc      |  109    109
Test Summary: | Pass  Total
mpfi_csch     |   16     16
Test Summary: | Pass  Total
mpfi_d_div    |   30     30
Test Summary: | Pass  Total
mpfi_diam_abs |   10     10
Test Summary: | Pass  Total
mpfi_div      |   62     62
Test Summary: | Pass  Total
mpfi_div_d    |   25     25
Test Summary: | Pass  Total
mpfi_d_sub    |   32     32
Test Summary: | Pass  Total
mpfi_exp      |   12     12
Test Summary: | Pass  Total
mpfi_exp2     |   13     13
Test Summary: | Pass  Total
mpfi_expm1    |   12     12
Test Summary: | Pass  Total
mpfi_hypot    |   17     17
Test Summary:  | Pass  Total
mpfi_intersect |   14     14
Test Summary: | Pass  Total
mpfi_inv      |   11     11
Test Summary: | Pass  Total
mpfi_is_neg   |   16     16
Test Summary:  | Pass  Total
mpfi_is_nonneg |   16     16
Test Summary:  | Pass  Total
mpfi_is_nonpos |   16     16
Test Summary: | Pass  Total
mpfi_is_pos   |   16     16
Test Summary:        | Pass  Total
mpfi_is_strictly_neg |   16     16
Test Summary:        | Pass  Total
mpfi_is_strictly_pos |   16     16
Test Summary: | Pass  Total
mpfi_log      |    7      7
Test Summary: | Pass  Total
mpfi_log1p    |    7      7
Test Summary: | Pass  Total
mpfi_log2     |    6      6
Test Summary: | Pass  Total
mpfi_log10    |    7      7
Test Summary: | Pass  Total
mpfi_mag      |   10     10
Test Summary: | Pass  Total
mpfi_mid      |   11     11
Test Summary: | Pass  Total
mpfi_mig      |   10     10
Test Summary: | Pass  Total
mpfi_mul      |   50     50
Test Summary: | Pass  Total
mpfi_mul_d    |   45     45
Test Summary: | Pass  Total
mpfi_neg      |    8      8
Test Summary: | Pass  Total
mpfi_put_d    |    3      3
Test Summary: | Pass  Total
mpfi_sec      |  109    109
Test Summary: | Pass  Total
mpfi_sech     |   14     14
Test Summary: | Pass  Total
mpfi_sin      |  128    128
Test Summary: | Pass  Total
mpfi_sinh     |   13     13
Test Summary: | Pass  Total
mpfi_sqr      |   11     11
Test Summary: | Pass  Total
mpfi_sqrt     |    7      7
Test Summary: | Pass  Total
mpfi_sub      |   19     19
Test Summary: | Pass  Total
mpfi_sub_d    |   32     32
Test Summary: | Pass  Total
mpfi_tan      |  128    128
Test Summary: | Pass  Total
mpfi_tanh     |   14     14
Test Summary: | Pass  Total
mpfi_union    |   14     14
Test Summary:          | Pass  Total
minimal.absRevBin_test |   24     24
Test Summary:        | Pass  Total
minimal_sqr_rev_test |   10     10
Test Summary:            | Pass  Total
minimal_sqr_rev_bin_test |   11     11
Test Summary:            | Pass  Total
minimal_sqr_rev_dec_test |   10     10
Test Summary:                | Pass  Total
minimal_sqr_rev_dec_bin_test |   11     11
Test Summary:        | Pass  Total
minimal_abs_rev_test |    9      9
Test Summary:            | Pass  Total
minimal_abs_rev_bin_test |    7      7
Test Summary:            | Pass  Total
minimal_abs_rev_dec_test |    9      9
Test Summary:                | Pass  Total
minimal_abs_rev_dec_bin_test |    7      7
Test Summary:         | Pass  Broken  Total
minimal_pown_rev_test |  135       8    143
Test Summary:             | Pass  Total
minimal_pown_rev_bin_test |   37     37
Test Summary:             | Pass  Broken  Total
minimal_pown_rev_dec_test |  134       8    142
Test Summary:                 | Pass  Total
minimal_pown_rev_dec_bin_test |   36     36
Test Summary:        | Pass  Total
minimal_sin_rev_test |    6      6
Test Summary:            | Pass  Total
minimal_sin_rev_bin_test |   20     20
Test Summary:            | Pass  Total
minimal_sin_rev_dec_test |    6      6
Test Summary:                | Pass  Total
minimal_sin_rev_dec_bin_test |   20     20
Test Summary:        | Pass  Total
minimal_cos_rev_test |    6      6
Test Summary:            | Pass  Total
minimal_cos_rev_bin_test |   21     21
Test Summary:            | Pass  Total
minimal_cos_rev_dec_test |    6      6
Test Summary:                | Pass  Total
minimal_cos_rev_dec_bin_test |   21     21
Test Summary:        | Pass  Total
minimal_tan_rev_test |    5      5
Test Summary:            | Pass  Total
minimal_tan_rev_bin_test |   10     10
Test Summary:            | Pass  Total
minimal_tan_rev_dec_test |    5      5
Test Summary:                | Pass  Total
minimal_tan_rev_dec_bin_test |   10     10
Test Summary:         | Pass  Total
minimal_cosh_rev_test |    5      5
Test Summary:             | Pass  Total
minimal_cosh_rev_bin_test |    5      5
Test Summary:             | Pass  Total
minimal_cosh_rev_dec_test |    5      5
Test Summary:                 | Pass  Total
minimal_cosh_rev_dec_bin_test |    5      5
Test Summary:        | Pass  Total
minimal_mul_rev_test |  172    172
Test Summary:            | Pass  Total
minimal_mul_rev_ten_test |    5      5
Test Summary:            | Pass  Total
minimal_mul_rev_dec_test |   10     10
Test Summary:                | Pass  Total
minimal_mul_rev_dec_ten_test |    5      5
Test Summary:             | Pass  Total
minimal_mulRevToPair_test |  172    172
Test Summary:                 | Pass  Total
minimal_mulRevToPair_dec_test |  175    175
Test Summary:        | Pass  Broken  Total
minimal.powRev1_test |  338      91    429
Test Summary:        | Pass  Broken  Total
minimal.powRev2_test |  233     142    375
     Testing IntervalArithmetic tests passed 

(@v1.7) pkg>

**Comment by lbenet** [comment]
Sorry for the long time to respond... I see no *errors* in the tests, though you are right, there are some broken tests. We are (very) slowly trying to fix them...

**Comment by lucaferranti** [comment]
yep, basically `@test_broken` means: I know this doesn't work and I am planning to fix it eventually, but due to limited bandwidth I cannot do it right now. 


Broken tests are also a great for new contributors who are wondering how to get started :)
