### ISSUE TITLE
replace `StaticArrays.jl` with `StaticArraysCore.jl`

### ISSUE THREAD

**Issue by lucaferranti** [JuliaIntervals/IntervalArithmetic.jl#542]
from a conversation with @schillic in zulip

> StaticArrays has outsourced the core code to StaticArraysCore. Maybe in IntervalArithmetic you can switch to that package instead, which loads much faster

**Comment by schillic** [comment]
I tried it out and it does not work. `StaticArraysCore` only defines the interface, but you cannot use it. Since functionality like `SVector` is actually used here in `IntervalBox`, it does not make sense to use `StaticArraysCore`. So I think this issue can be closed, sorry.

**Comment by lucaferranti** [comment]
I haven't looked at `StaticArraysCore` at all, but maybe it could still be used by parametrizing `IntervalBox` over the vector type and relying on functions like `typeof` etc. instead of hard-coding `SVector` ?

**Comment by schillic** [comment]
When I tried the change, the tests failed here:

https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/9813b95655d4319439baba6833028b82ff84e993/src/multidim/intervalbox.jl#L12

For that you need the `SVector` type and not just an interface.

**Comment by Kolaru** [comment]
The whole dependency will be removed by #550.

If we ever bring back IntervalBox, we'll consider that again.
