### ISSUE TITLE
What is the best way for interval evaluation of a function with Vector{AbstractFloat} argument ?

### ISSUE THREAD

**Issue by d-monnet** [JuliaIntervals/IntervalArithmetic.jl#546]
Hi there,
I need to evaluate in a reliable way functions with Vector{AbstractFloat} inputs. I couldn't find in the documentation how to do it, so far what I'm doing to evaluate `f` at `x` with interval is
```julia
julia> using IntervalArithmetic

julia> f(x) = x[1] + x[2]
f (generic function with 1 method)

julia> x = ones(2)
2-element Vector{Float64}
  1.0
  1.0
julia> X = IntervalBox(x) # easy but probably a bad way to instanciate X
[1, 1]²

julia> f(X) 
[2, 2]
```
What would be the proper way to do it ?
I would also have the same question for vector valued functions.

With the way I do it, I ran into some issues like:
```julia
julia> x = [1/10,1/10]
2-element Vector{Float64}
  0.1
  0.1

julia> X = IntervalBox(x)
[0.1, 0.00001]²

julia> F = f(X)
[0.2, 0.200001]

julia> diam(F) === 0.0
true
```
I use IntervalArithmetic.jl v0.20.7 and Julia 1.7.1.

**Comment by lbenet** [comment]
Hi!
We have different ways to create `IntervalBox`-es. You may find the following handy:
```julia
julia> Interval(1,2) × Interval(2,3)
[1, 2] × [2, 3]

julia> IntervalBox(Interval(1,2), Interval(2,3))
[1, 2] × [2, 3]
```

Let me note that the following (interval) constructors yield two distinct intervals:
```julia
julia> @format full;   # in order to display the whole Float64 numbers

julia> x1 = Interval(1/10)
Interval(0.1, 0.1)

julia> x2 = (1/10) .. (1/10) # equivalent to `@interval(1/10)
Interval(0.09999999999999999, 0.1)
```
The subtlety is that the `..` and `@interval` construct intervals that include rounding, to be sure that the number (e.g. `1/10`, which may not be exactly represented as a floating point) is inside the interval. Hence,
```julia
julia> 1//10 ∈ x1
false

julia> 1//10 ∈ x2
true
```

Now, going back to the evaluation of `f`:
```julia
julia> X1 = IntervalBox(x1, x1) # thin intervals in each dimension !
IntervalBox(Interval(0.1, 0.1), 2)

julia> X2 = IntervalBox(x2, x2)
IntervalBox(Interval(0.09999999999999999, 0.1), 2)

julia> f(X1) 
Interval(0.2, 0.2)

julia> f(X2)
Interval(0.19999999999999998, 0.2)
```
This shows why `f(X1)` has zero width while `f(X2)` doesn't.

I hope this clarifies the results.

**Comment by d-monnet** [comment]
Thanks for the clarification.

So, following what you explained, the proper way to evaluate a function with interval would be something like
```julia
julia> using IntervalArithmetic

julia> using Random

julia> f(x) = sum(x)
f (generic function with 1 method)

julia> Random.seed!(1) # for reproductibility of example
TaskLocalRNG()

julia> x = rand(10)
10-element Vector{Float64}:
 0.0491718221481211
 0.11907881640750706
 0.3932710232252806
 ⋮
 0.8557176841095734
 0.8025607099234905
 0.661425351684768

julia> X = [x[i]..x[i] for i = 1:length(x)]
10-element Vector{Interval{Float64}}:
 [0.0491718, 0.0491719]
 [0.119078, 0.119079]
 [0.393271, 0.393272]
  ⋮
 [0.855717, 0.855718]
 [0.80256, 0.802561]
 [0.661425, 0.661426]

F = f(X)
[4.45194, 4.45195]

```
?

Would it be possible to avoid the allocation of X to improve the performance ?

**Comment by dpsanders** [comment]
As @lbenet was saying, prefer to use `IntervalBox`, which uses `StaticVector`s:
```jl
julia> X = IntervalBox(x)
[0.0491718, 0.0491719] × [0.119078, 0.119079] × [0.393271, 0.393272] × [0.0240943, 0.0240944] × [0.691857, 0.691858] × [0.767518, 0.767519] × [0.087253, 0.0872531] × [0.855717, 0.855718] × [0.80256, 0.802561] × [0.661425, 0.661426]

julia> using BenchmarkTools

julia> @btime f($X)
  91.122 ns (0 allocations: 0 bytes)
[4.45194, 4.45195]
```

**Comment by dpsanders** [comment]
In general to get best performance the dimension (length of vector) needs to be a compile-time constant. What is your use case?

**Comment by dpsanders** [comment]
Basically if you create your vector as an `SVector` from `StaticArray`s things should work properly and performantly.

**Comment by d-monnet** [comment]
Thanks for the reply. 
In my case I use interval evaluation for guaranteed evaluation of the objective function and gradient in non-convex optimization context, so the size of x is fixed (dimension of the problem).

I'm sorry I'm a bit confused here:
> ```julia
> julia> X = IntervalBox(x)
> [0.0491718, 0.0491719] × [0.119078, 0.119079] × [0.393271, 0.393272] × [0.0240943, 0.0240944] × [0.691857, 0.691858] × [0.767518, 0.767519] × [0.087253, 0.0872531] × [0.855717, 0.855718] × [0.80256, 0.802561] × [0.661425, 0.661426]
> ```
Is this a "safe" way to build an IntervalVector ? Going back to my initial post and @lbenet answer,
```julia
julia> using IntervalArithmetic

julia> x = [0.1,0.1]
2-element Vector{Float64}:
 0.1
 0.1

julia> Xbad = IntervalBox(x) # bad instanciation of IntervalBox
[0.1, 0.100001]²

julia> Fbad = f(Xbad)
[0.2, 0.200001]

julia> diam(Fbad)===0.0 
true

julia> Xgood = [x[i]..x[i] for i=1:length(x)] # good instanciation, could use static array too
2-element Vector{Interval{Float64}}:
 [0.0999999, 0.100001]
 [0.0999999, 0.100001]

julia> Fgood = f(Xgood)
[0.199999, 0.200001]

julia> diam(Fgood)
2.7755575615628914e-17
```

**Comment by OlivierHnt** [comment]
Closing this issue since it looks solved. `IntervalBox` is a mere wrapper for `AbstractVector`, so both of your instantiations `Xbad` and `Xgood` are correct. The point, however, is that these represent different intervals (`IntervalBox` does not do any rounding while `..` does`).

Also, on master, this is no longer true since the `..` constructor does not do any rounding.
