### ISSUE TITLE
Non-allocating version of set operations

### ISSUE THREAD

**Issue by wolthom** [JuliaIntervals/IntervalArithmetic.jl#551]
If I'm reading the API reference of `Base.setdiff` on `IntervalBoxes` correctly, there is currently no non-allocating version of this method ([API Reference](https://juliaintervals.github.io/IntervalArithmetic.jl/latest/api/#Base.setdiff-Union{Tuple{T},%20Tuple{N},%20Tuple{IntervalBox{N,T},IntervalBox{N,T}}}%20where%20T%20where%20N)).

Would it make sense to add a non-allocating version that accepts a buffer as first argument? `Base.setdiff!` does exist, but has slightly different semantics than this case would provide.

The implementation would probably be fairly simple by extracting the push-into-array logic out from here: [`Base.setdfiff` implementation](https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/2d021b42330722eed7f1e8985895875a005c922a/src/multidim/setdiff.jl#L31-L49)

**Comment by dpsanders** [comment]
Yes that's a good idea, thanks! Would you like to make a PR? I also had thought about a version that returned an SVector instead, since you know the maximum number of boxes in the result.

**Comment by wolthom** [comment]
Sure, this sounds interesting and doable :)
Any other methods that could use a non-allocating version?

Do you have StaticArrays as a dependency anyway? Otherwise this could be a bit heavy in terms of loading times. 
Also, how would the interface look like? Would it return `SVector{Union{Nothing, IntervalBox}}`?
