### ISSUE TITLE
Make DecoratedInterval the default

### ISSUE THREAD

**Issue by Kolaru** [JuliaIntervals/IntervalArithmetic.jl#584]
It has been discussed during the JuliaInterval call a couple of time, but without a clear consensus yet.

I think it would be good to have `DecoratedInterval` as the default. A new user would be warn when something weird happen, and that's probably what we want for them.

As they become more advanced, they could discover the faster, less safe `Interval` without too much trouble.

Of course that would mean, renaming `DecoratedInterval` to `Interval`, and `Interval` to `BareInterval`.

**Comment by OlivierHnt** [comment]
One advantage of doing this is that we can reintroduce conversion (implicit or explicit) with numbers for `DecoratedInterval` by adding a specific decoration.
While `BareInterval` would be more conservative to avoid confusion. E.g. `bareinterval(1) + 1` could either error, or return a `DecoratedInterval` with the correct decoration 🤔
