### ISSUE TITLE
Make sure that the documentation is correct

### ISSUE THREAD

**Issue by Kolaru** [JuliaIntervals/IntervalArithmetic.jl#591]
A lot of change have happened, and the documentation did not fully follow.

For example, some of the examples still use `IntervalBox`.

As discussed during today's call, once #584 is merge, this is the last issue to be fix before we move on to release 1.0 (first with a transition period with v0.22 that will give us time to update the downstream packages of the JuliaIntervals organization and make sure IntervalArithmetic in its new form is okay).

It doesn't need to be pretty for v1.0, just to be correct.

**Comment by OlivierHnt** [comment]
Also, we should keep an eye on #524.
