### ISSUE TITLE
Plotting intervals after removal of `IntervalBox`

### ISSUE THREAD

**Issue by Joel-Dahne** [JuliaIntervals/IntervalArithmetic.jl#605]
I have often made use of `IntervalBox` for plotting enclosures of functions. With the removal of `IntervalBox` in 0.22 this is no longer possible. Is there some other convenient way of plotting interval enclosures? In the [documentation](https://juliaintervals.github.io/pages/tutorials/tutorialArithmetic/) at juliaintervals.github.io is still makes use of `IntervalBox`, but I believe that is outdated?

The removal of `IntervalBox` seems to be missing from the [NEWS.md](https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/master/NEWS.md) file as well. As a side note it would be great to link to the NEWS.md file in the releases! It took me some time before I found it.

**Comment by OlivierHnt** [comment]
Thanks for the feedback!

Yes juliaintervals.github.io is outdated for the moment 😞. Thx for pointing out the missing entry in the NEWS.md, I added an entry.

Indeed, the plotting recipes for multi-dimensional boxes has been removed; I do not think that this depends on whether we have some `IntervalBox` structure defined. Any instance of `IntervalBox` is now simply some instance of `AbstractVector{<:Interval}`.

So the previous code for plotting recipes would now read:

```Julia
using RecipesBase

@recipe function f(xx::AbtrstactVector{<:Interval})
    @assert length(xx) == 2
    x, y = xx

    seriesalpha --> 0.5
    seriestype := :shape

    x = [inf(x), sup(x), sup(x), inf(x)]
    y = [inf(y), inf(y), sup(y), sup(y)]

    x, y
end

@recipe function f(v::AbstractVector{<:AbtrstactVector{<:Interval}})
    seriestype := :shape

    xs = Float64[]
    ys = Float64[]

    # build up coords: # (alternative: use @series)
    for xx in v
        x, y = xx
        # use NaNs to separate
        append!(xs, [inf(x), sup(x), sup(x), inf(x), NaN])
        append!(ys, [inf(y), inf(y), sup(y), sup(y), NaN])
    end

    seriesalpha --> 0.5

    xs, ys
end
```

What we should do is
1. make sure this is still the way recipes are defined for [Plots.jl](https://github.com/JuliaPlots/Plots.jl) and probably add it as a package extension
2. do the same for [Makie.jl](https://github.com/MakieOrg/Makie.jl)

Btw, if you have some experience with plotting recipes, that would be helpful.

**Comment by Joel-Dahne** [comment]
That makes sense! Adding an extension for this seems reasonable, if nothing else it is heavily used in the documentation!

I have some experience with plotting recipes, but they are mostly bad... This is in fact the main reason I have used the ones in IntervalArithmetic.jl. I do most of my calculations with Arblib.jl but have converted to intervals for plotting to avoid having to handle plotting recipes. I can maybe take a look at it at some point, but I don't promise anything 😅

Great job with all the recent work by the way! It has required some refactoring on my end, even though I only make use of the package for a very small part of my work. But in general I think the recent changes have been very sound!

**Comment by OlivierHnt** [comment]
Thanks 🙂 !

Oh just in case, we also deploy a documentation on this repo: https://juliaintervals.github.io/IntervalArithmetic.jl/stable
While it is still a little scarce, at least it should be reliable.
We need juliaintervals.github.io to point to it, instead of having its own (now outdated) documentation.

**Comment by OlivierHnt** [comment]
@Joel-Dahne
Please re-open an issue if PR #608 was not sufficient for your needs (it should give you back the functionalities in v0.20 of IntervalArithmetic).
This is part of the 0.22.4 release (give it about 10 minutes to be tagged and available).
