### ISSUE TITLE
Non-thread safe use of `setrounding`

### ISSUE THREAD

**Issue by Joel-Dahne** [JuliaIntervals/IntervalArithmetic.jl#612]
The slow versions of the `_round` methods in `src/interval/rounding.jl` use `BigFloat` together with `setrounding` in a way that is not thread-safe. For `setprecision` there is a `precision_lock` defined at the top of the file that is used to make it thread-safe, but not such look is used for the `setrounding`. Starting Julia with two threads I could reliably produce errors with the following code
```julia
x = interval(BigFloat, 1)
y = sin(x)
Threads.@threads for _ in 1:1000
    z = sin(x)
    @assert isequal_interval(y, z)
end
```
In many cases (though not all) I also found that after running this loop even the non-threaded behavior is wrong. Most of the time this fails:
```julia
setrounding(BigFloat, RoundNearest) # Reset rounding in case this would be an issue
z = sin(x)
@assert isequal_interval(y, z)
```
So there is some global state that gets messed up.

I made a quick attempt at fixing this by adding locks around `setround`, but I could still not get it to work properly. So there might be something else that I'm missing as well.

**Comment by Joel-Dahne** [comment]
Some more details, maybe it helps someone with the debugging...

I can reproduce it also with the code
```julia
x = bareinterval(BigFloat, 1)
y = sin(x)
Threads.@threads for _ in 1:100000
    z = IntervalArithmetic._unsafe_bareinterval(BigFloat, IntervalArithmetic._sin_round(x.lo, RoundDown), IntervalArithmetic._sin_round(x.hi, RoundUp))
    if !isequal_interval(y, z)
        @show y z
    end
end
```
BUT, for this code my attempt at adding locks for the use of `setrounding` seems to work. I don't know why this is the case, as far as I understand the codes should do more or less the same.

**Comment by dpsanders** [comment]
Ugh, `setrounding` has always been a mess, and `BigFloat`s have always had too much global state.

I suggest using the `accurate` mode (or whatever it is now called) that just uses `prevfloat` and `nextfloat` for rounding.

**Comment by dpsanders** [comment]
But of course it would be great to get this fixed too.

**Comment by Joel-Dahne** [comment]
Thinking more about it, it would not be enough to use locks anyway since any other part of the program could still change the rounding mode. The same holds true for the `precision_lock` that guards the `setprecision`.

I think the simplest solution is to just call MPFR directly and not use the `BigFloat` interface. So for example `_add_round` would become
```julia
function _add_round(::IntervalRounding{:slow}, x::BigFloat, y::BigFloat, r::RoundingMode)
    @assert precision(x) == precision(y) # Should this be required?
    z = BigFloat(precision = precision(x))
    @ccall Base.MPFR.libmpfr.mpfr_add(
        z::Ref{BigFloat},
        x::Ref{BigFloat},
        y::Ref{BigFloat},
        r::Base.MPFR.MPFRRoundingMode,
    )::Int32
    return z
end
```

**Comment by Joel-Dahne** [comment]
> Ugh, `setrounding` has always been a mess, and `BigFloat`s have always had too much global state.
> 
> I suggest using the `accurate` mode (or whatever it is now called) that just uses `prevfloat` and `nextfloat` for rounding.

The `:fast` rounding seems to be deprecated. The docstring for `IntervalRounding` mentions it as unsupported and the implementations of it are commented our in the source code. 

But I can mention that this bug is not an issue for me in practice. I'm currently looking at to what extent it would be possible to have Arblib.jl and IntervalArithmetic.jl work together. For that I have needed to look at a lot of the implementations to see what is really required. That's when I spotted this bug!

**Comment by OlivierHnt** [comment]
Ah we need to fix this asap. I will look into the proposed solution https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/612#issuecomment-1884360672

Indeed, the `:accurate` mode (now called as `:fast`) is not supported due to #374. Since the number of ulp also depends on the system's architecture, I did not take the time to fix this yet.

**Comment by OlivierHnt** [comment]
Yes, I noticed this as well. Presumably, we ought to do `T(1//10, RoundDown)` and `T(1//10, RoundUp)` where `T<:AbstractFloat`

**Comment by OlivierHnt** [comment]
Perhaps I misunderstand your comment. The moment `_sin_round`, or any other internal rounding function, is called, the rounding direction is prescribed (whether the function is increasing or not has been determined before).
To be more specific we would have something in the vein of

```Julia
_sin_round(x::Rational{T}, r::RoundingMode) where {T<:Integer} = _sin_round(interval_rounding(), float(T)(x, r), r)
```

**Comment by OlivierHnt** [comment]
Mhm so adding a lock before calling CRlibm functions fixes the error from https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/612#issuecomment-1883776832

But executing

```Julia
x = interval(BigFloat, 1)
y = sin(x)
Threads.@threads for _ in 1:1000
    z = sin(x)
    @assert isequal_interval(y, z)
end
```

still errors.
In fact, the precision of `BigFloat` changes after! E.g.

```Julia
julia> Threads.@threads for _ in 1:100000
           z = sin(x)
           # @assert isequal_interval(y, z)
           if !isequal_interval(y, z)
               @show y z
               error()
           end
       end
y = BareInterval{BigFloat}(0.8414709848078965066525023216302989996225630607983710656727517099919104043912312, 0.8414709848078965066525023216302989996225630607983710656727517099919104043912398)
y = BareInterval{BigFloat}(0.8414709848078965066525023216302989996225630607983710656727517099919104043912312, 0.8414709848078965066525023216302989996225630607983710656727517099919104043912398)
y = BareInterval{BigFloat}(0.8414709848078965066525023216302989996225630607983710656727517099919104043912312, 0.8414709848078965066525023216302989996225630607983710656727517099919104043912398)
z = BareInterval{BigFloat}(0.8414709848078965066525023216302989996225630607983710656727517099919104043912312, 0.8414709848078965066525023216302989996225630607983710656727517099919104043912396689486415)
y = BareInterval{BigFloat}(0.8414709848078965066525023216302989996225630607983710656727517099919104043912312, 0.8414709848078965066525023216302989996225630607983710656727517099919104043912398)
y = BareInterval{BigFloat}(0.8414709848078965066525023216302989996225630607983710656727517099919104043912312, 0.8414709848078965066525023216302989996225630607983710656727517099919104043912398)
z = BareInterval{BigFloat}(0.8414709848078965066525023216302989996225630607983710656727517099919104043912312, 0.8414709848078965066525023216302989996225630607983710656727517099919104043912396689486415)
z = BareInterval{BigFloat}(0.84147098480789650665250232163029899962256306079837106567275170999191040439123966894863974354305248, 0.8414709848078965066525023216302989996225630607983710656727517099919104043912396689486415)
z = BareInterval{BigFloat}(0.8414709848078965066525023216302989996225630607983710656727517099919104043912396689486395, 0.8414709848078965066525023216302989996225630607983710656727517099919104043912396689486415)
z = BareInterval{BigFloat}(0.8414709848078965066525023216302989996225630607983710656727517099919104043912312, 0.8414709848078965066525023216302989996225630607983710656727517099919104043912396689486415)
ERROR: TaskFailedException

    nested task error: 
    Stacktrace:
     [1] error()
       @ Base ./error.jl:44
     [2] macro expansion
       @ ./REPL[78]:6 [inlined]
     [3] (::var"#287#threadsfor_fun#53"{var"#287#threadsfor_fun#52#54"{UnitRange{Int64}}})(tid::Int64; onethread::Bool)
       @ Main ./threadingconstructs.jl:214
     [4] #287#threadsfor_fun
       @ Main ./threadingconstructs.jl:181 [inlined]
     [5] (::Base.Threads.var"#1#2"{var"#287#threadsfor_fun#53"{var"#287#threadsfor_fun#52#54"{UnitRange{Int64}}}, Int64})()
       @ Base.Threads ./threadingconstructs.jl:153

...and 7 more exceptions.

Stacktrace:
 [1] threading_run(fun::var"#287#threadsfor_fun#53"{var"#287#threadsfor_fun#52#54"{UnitRange{Int64}}}, static::Bool)
   @ Base.Threads ./threadingconstructs.jl:171
 [2] macro expansion
   @ ./threadingconstructs.jl:219 [inlined]
 [3] top-level scope
   @ ./REPL[78]:1

julia> precision(BigFloat)
288
```

Not sure what is going on...
