### ISSUE TITLE
Incorrect rounding for extreme irrationals

### ISSUE THREAD

**Issue by Joel-Dahne** [JuliaIntervals/IntervalArithmetic.jl#616]
See [52941](https://github.com/JuliaLang/julia/issues/52941) and my comment in #615.

The rounding of irrationals in Base Julia is not fully rigorous and can give incorrect results in extreme cases. This has as a consequence that intervals constructed from irrationals are not guaranteed to enclose them. For example, defining the irrational $1 - \pi^{-300}$ gives us
```julia
julia> Base.@irrational almost_one (1 - big(π)^-300)

julia> almost_one
almost_one = 1.0...

julia> Float64(almost_one, RoundDown)
1.0

julia> interval(almost_one)
[1.0, 1.0]_com

```
where the interval clearly doesn't contain the irrational.

For Base Julia these types of extreme cases are maybe fine to not get fully correct. For interval arithmetic not so much. I would propose to limit the construction of intervals from irrationals to only those irrationals which are implemented in `mpfr`, which are `Irrational{:π}`, `Irrational{:γ}` and `Irrational{:catalan}`. One could also support `Irrational{:ℯ}`, but one has to call `mpfr` directly since the regular constructor doesn't expose the rounding parameter.

Note that the constructors in `src/constructors.jl` under the comment 
```julia
# by-pass the absence of `BigFloat(..., ROUNDING_MODE)` (cf. base/irrationals.jl)
# for some irrationals defined in MathConstants (cf. base/mathconstants.jl)
```
are not safe, as by the above the rounding to `Float64` is not safe.

**Comment by OlivierHnt** [comment]
Indeed.. Hopefully PR #617 addresses this issue correctly.
