### ISSUE TITLE
`string(x::Interval)` is not working correctly

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#643]
```jl
julia> using IntervalArithmetic

julia> x = interval(1, 2)
[1.0, 2.0]_com

julia> string(x)
"Interval{Float64}(1.0, 2.0, com)"
```

`string(x)` should return the string version of what is displayed.

This points to a possible issue in the implementation of `Base.show(io::IO, x::Interval)`

**Comment by OlivierHnt** [comment]
Good catch. Should be fixed with the PR #644.
