### ISSUE TITLE
Add `\infty` symbol to Symbols module

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#658]
Can we add the `\infty` symbol to the Symbols module or is there a reason why it was excluded?

**Comment by OlivierHnt** [comment]
Yes this was purposely removed: there were conflicts with commonly used libraries which export the name, and `\infty` has nothing to do with intervals (unlike all symbols contained in the module IntervalArithmetic.Symbols) (see also the related issue #270).
