### ISSUE TITLE
Reinstate fast rounding with `prevfloat` and `nextfloat`

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#665]
The IEEE 758 standard for floating-point arithmetic guarantees that `+`, `-`, `*`, `/` and `sqrt` are faithfully rounded.

Thus directed rounding with `prevfloat` and `nextfloat` does give a guaranteed enclosure for interval arithmetic computations using those operations.

In particular this is enough for fast guaranteed enclosure of the range of polynomials.

**Comment by OlivierHnt** [comment]
Sounds good. Are there tests in the Julia repo on this?

**Comment by dpsanders** [comment]
Julia is just exposing the cpu operations, which must follow the floating point standard. But good question about tests, I don't know.
