### ISSUE TITLE
Document the decoration and flag system

### ISSUE THREAD

**Issue by Kolaru** [JuliaIntervals/IntervalArithmetic.jl#671]
In particular since it is necessary to understand the v0.22 breaking changes, that could also help  downstream packages to go forward (see #668 ).

**Comment by OlivierHnt** [comment]
This is already done no ? See https://juliaintervals.github.io/IntervalArithmetic.jl/stable/manual/construction/#Guarantee

**Comment by Kolaru** [comment]
Hmm I missed it, I would still make it a separate section, it's not so clear to me that decorations are a subset of constructing intervals.

**Comment by OlivierHnt** [comment]
Yea I agree, there is definitely some polishing to do in the docs.
