### ISSUE TITLE
Introduce `IntervalType` for union of `Interval` and `BareInterval`

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#678]
In packages like IntervalConstraintProgramming I often need to refer to the `Union` of `Interval` and `BareInterval`. Currently I need to define that union in each package.

I propose to export

`const IntervalType{T} = Union{Interval{T}, BareInterval{T}}`

from IntervalArithmetic.jl.

**Comment by OlivierHnt** [comment]
That sounds reasonable. One note: we export the aliases

```Julia
const RealOrComplexI{T} = Union{Interval{T},Complex{Interval{T}}}
const ComplexI{T} = Complex{Interval{T}}
```

So maybe the naming `IntervalType` is misleading as it does not include `ComplexI`. Maybe

```
const RealIntervalType{T} = Union{BareInterval{T},Interval{T}}
```

is less ambiguous? Or do you have an other suggestion?

**Comment by dpsanders** [comment]
Ah I didn't realise that, thanks.
Yes RealIntervalType sounds good. Or just RealInterval?
