### ISSUE TITLE
`IntervalBox` doesn't appear in the documentation

### ISSUE THREAD

**Issue by nsajko** [JuliaIntervals/IntervalArithmetic.jl#681]

**Comment by dpsanders** [comment]
IntervalBox is now provided by a separate package:
https://github.com/JuliaIntervals/IntervalBoxes.jl

**Comment by OlivierHnt** [comment]
Btw the functionalities for `IntervalBoxe` are still part of IntervalArithmetic (e.g. `bisect`, `intersect_interval`, `union_interval`, etc.), but now a multi-dimensional interval is just some `AbstractVector{<:Interval}`.

Do not hesitate to re-open this issue if you'd like to discuss this more, or run into some problems/missing functionalities 🙂
