### ISSUE TITLE
`interval(-Inf)` should do the useful thing

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#688]
```jl
julia> interval(-Inf)
┌ Warning: ill-formed interval [a, b] with a = -Inf, b = -Inf and decoration d = com. NaI is returned
└ @ IntervalArithmetic ~/Dropbox/packages/IntervalArithmetic/src/intervals/construction.jl:446
∅_ill
```

IMO This should return `-Inf..(nextfloat(-Inf))` instead

**Comment by OlivierHnt** [comment]
Our hands are tied by the standard on interval arithmetic on this. Indeed, the only current flavour supported by IntervalArithmetic.jl is the "set based flavour" which states that $\infty$ can never be part of an interval.

If I recall correctly (to check), what you want is the behaviour described by the "c-set flavour", which is not currently implemented. I am closing this issue as it is the desired result. Note, we could open an issue about implementing the "c-set flavour" (though we may lack the man power at the moment to tackle this).

**Comment by dpsanders** [comment]
I would argue that `-Inf` is the representation in floating point for any number smaller than `typemin(Float64)`. The correct result for `interval(-Inf)` is then "the smallest floating-point interval containing that number", which would be `-Inf..(nextfloat(-Inf))`. 

I don't believe the standard says anything about this case?

**Comment by OlivierHnt** [comment]
For this we have to look at the IEEE Standard for Floating-Point Arithmetic (IEEE Std 754-2019, page 48):

> The behavior of infinity in floating-point arithmetic is derived from the limiting cases of real arithmetic
with operands of arbitrarily large magnitude, when such a limit exists. Infinities shall be interpreted in the
affine sense, that is: $-\infty < \text{every finite number} < +\infty$.

**Comment by dpsanders** [comment]
OK fair enough I guess, thanks!

**Comment by dpsanders** [comment]
Is there a convenience function to make the interval I want?

**Comment by OlivierHnt** [comment]
Yes

```Julia
julia> typemax(Interval{Float64})
[1.79769e+308, ∞)_dac

julia> typemin(Interval{Float64})
(-∞, -1.79769e+308]_dac
```
