### ISSUE TITLE
Use === when possible instead of ==`

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#69]
to compare bit strings.

e.g.
```
Base.isempty(x::Interval{Float64}) = x.lo === Inf && x.hi === -Inf
```

**Comment by dpsanders** [comment]
This *may* be faster.

**Comment by lbenet** [comment]
@lucaferranti Can you point out where was this completed? Or do you mean the implementation in the `1.0-dev` branch (`≛` and `==`)? In any case, I'm not sure we use `===` in those functions...

**Comment by lbenet** [comment]
@lucaferranti Can you point out where was this completed? Or do you mean the implementation in the `1.0-dev` branch (`≛` and `==`)? In any case, I'm not sure we use `===` in those functions...

**Comment by lucaferranti** [comment]
today with @Kolaru we went through issues and closed the ones that seemed trivially completed / not relevant.

For this, iirc the reasoning was that it's unlikely to give and speed-up and prob not worth pursuing. Also note that `===` cannot be used with BigFloats

```julia
julia> a = big(1.0)
1.0

julia> b = big(1.0)
1.0

julia> a === b
false
```

if you would like to do more thoughtful benchmarks, feel free to reopen
