### ISSUE TITLE
prev_float(::BigFloat) is missing

### ISSUE THREAD

**Issue by kalmarek** [JuliaIntervals/IntervalArithmetic.jl#72]
at https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/master/src/intervals/rounding.jl#L131
arithmetic operations are defined for all `T<:AbstractFloats`, but `prev_float` (in `AdjacentFloats.jl`) is defined only for `Float{16, 32, 64}`.
This gets emanated in 

```
ERROR: LoadError: MethodError: no method matching prev_float(::BigFloat)
Closest candidates are:
  prev_float(!Matched::Float16) at /home/kalmar/.julia/v0.5/AdjacentFloats/src/AdjacentFloats.jl:35
  prev_float(!Matched::Float32) at /home/kalmar/.julia/v0.5/AdjacentFloats/src/AdjacentFloats.jl:31
  prev_float(!Matched::Float64) at /home/kalmar/.julia/v0.5/AdjacentFloats/src/AdjacentFloats.jl:21
  ...
 in *(::IntervalArithmetic.Interval{BigFloat}, ::IntervalArithmetic.Interval{BigFloat}) at /home/kalmar/.julia/v0.5/IntervalArithmetic/src/intervals/arithmetic.jl:84
```
(this used to work on v0.9.1) 

```
Julia Version 0.5.2
Commit f4c6c9d4bb* (2017-05-06 16:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE NO_AFFINITY HASWELL)
  LAPACK: liblapack
  LIBM: libm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake-avx512)
```
IntervalArithmetic v0.10.0

**Comment by dpsanders** [comment]
Oops, thanks for catching this. I'll fix tomorrow

**Comment by dpsanders** [comment]
This just needs a definition
`AdjacentFloats.prev_float(x) = prevfloat(x)`

**Comment by kalmarek** [comment]
Thanks. Don't forget to define `nextfloat` as well ;-)

**Comment by dpsanders** [comment]
What context did you find this in? Can this be turned into a test case?
These should probably be defined directly in the AdjacentFloats package.

**Comment by dpsanders** [comment]
Yes that would be great, thanks!

**Comment by JeffreySarnoff** [comment]
fixed in master, submitted as new release

**Comment by JeffreySarnoff** [comment]
merged

**Comment by kalmarek** [comment]
I will try to submit a test

**Comment by kalmarek** [comment]
Ok, test case for this turned out to be easier than expected:
```julia
using IntervalArithmetic
setrounding(Interval, :accurate)
w = 0 ± big(0.1)
w*w
```
(or any function that uses `directed` in rounding, e.g. `:+, :-, :*, :/, :atan2, :^, :sqrt, :inv, :tanh, :asinh, :acosh, :atanh` and all of `CRlibm`)
The catch is it happens only on `:accurate` rounding and `julia-v0.5` does not recompile functions after running `setrounding`. So an eventual test:
 * would have to start at the beginning of session
 * set rounding before any of these are used
 * run tests caching possible `MethodError: no method matching prev_float(::BigFloat)`

I didn't look much into tests for `Intervals`, but how feasible are those conditions?

**Comment by dpsanders** [comment]
0.5 support has been dropped in the latest version so that is no longer an issue. 

It would be great if you could make a pull request with your suggested test code!

**Comment by kalmarek** [comment]
Should these be placed in IntervalArithmetic.jl/test/interval_tests/rounding.jl ?
since it's the definition of `prevfloat`, `nextfloat` should we test all of the functions above, or just `+` is enough?

**Comment by dpsanders** [comment]
Fixed upstream in latest release of AdjacentFloats.jl.
