### ISSUE TITLE
`entireinterval` is not a very good name

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#8]
It is the entire real line.

cc @lbenet

**Comment by lbenet** [comment]
I proposed that name inspired in the ieee standard. There, the `entire` interval is defined as `Interval(-Inf,Inf)`. I proposed that name since `entire` is not clear enough. You are right that `entireinterval` corresponds to the entire real line (as an interval!). Since `Interval` refers to the one-dimensional case, whereas IntervalBox is for the multidimensional case, I think is ok. Do you have an alternative for the name of that function?

**Comment by dpsanders** [comment]
I agree that `entire` is not clear enough.
Maybe `entirerealline` (ugly) / `wholerealline` / `allreals` (I think that is used in some package I have seen)

**Comment by dpsanders** [comment]
On the other hand, if it is not exported and is `IntervalArithmetic.entire()`, then maybe it is clear enough, but not very nice to write.

For what it's worth, I like just writing `-∞..∞`, although it does need quite a lot of typing. Writing `-Inf..Inf` is actually shorter (in terms of number of keystrokes) than any option involving the word `entire` with parentheses ;)

**Comment by dpsanders** [comment]
How about just `reals()`?

**Comment by lbenet** [comment]
From the suggestions, those names do not make clear that the result is an interval (which happens to be the whole real line). I agree with you that, from the point of view of the number of keystrokes, `-Inf..Inf` seems the best option, though I think the standard requires a specific function for that.

**Comment by dpsanders** [comment]
I see your point. How about `realline()`? That does sound like a set.

**Comment by dpsanders** [comment]
Here's an idea: IR

**Comment by dpsanders** [comment]
We could even have e.g. `RR(3)` for `IntervalBox(-Inf..Inf, -Inf..Inf, -Inf..Inf)`

**Comment by dpsanders** [comment]
Note that Julia also has "blackboard bold" ("double-struck") letters, e.g. `\BbbR` gives `ℝ`

**Comment by lbenet** [comment]
Yes, let's try it with `RR()`!

**Comment by dpsanders** [comment]
Now `\bbR`. But unfortunately 
```
julia> ℝ = -∞..∞
[-∞, ∞]

julia> ℝ^3
[-∞, ∞]
``` 
(of course). Although, we do have

```
julia> ℝ × ℝ
[-∞, ∞] × [-∞, ∞]
```

**Comment by dpsanders** [comment]
And 
```
julia> IntervalBox(ℝ, 4)
[-∞, ∞] × [-∞, ∞] × [-∞, ∞] × [-∞, ∞]
```

**Comment by Kolaru** [comment]
`entireinterval` is fine enough, symbols will be exported in a separate module in 1.0-dev, see #270
