### ISSUE TITLE
Bisection should ignore atomic intervals

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#84]

**Comment by dpsanders** [comment]
And return an indication of whether the intervalbox is atomic (ie atomic on each direction)

**Comment by dpsanders** [comment]
Note that a box is atomic only if each interval in the box is.

**Comment by dpsanders** [comment]
Probably it should return `(X, ∅)` if `X` is atomic.

**Comment by Kolaru** [comment]
> Note that a box is atomic only if each interval in the box is.

This is true, but we will have to be careful: the non atomic dimension may not be the biggest one.

```jl
julia> X = IntervalBox(0..1, 10.0^100..nextfloat(10.0^100))
[0, 1] × [9.99999e+99, 1.00001e+100]

julia> bisect(X)
([0, 1] × [9.99999e+99, 1.00001e+100], [0, 1] × [1e+100, 1.00001e+100])
```

Also this doesn't seem to be part of the standard (freedom !), and I like the `(X, ∅)` proposition.

**Comment by dpsanders** [comment]
Good point! That will be tricky to handle. 

I guess broadcast isatomic over the IntervalBox and bisect the first dimension that is not atomic.
