### ISSUE TITLE
Performance: simplify constructor

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#9]
In the branch `simplify_constructor`, the inner constructor of `Interval`, that performs checks for a valid interval, is removed.

The goal of this is performance: constructing an `Interval` goes down from 9ns to 1.5ns, and `Interval`s are constructed all the time in real code.

I propose an `interval` (with small `i`) function that carries out the current checks when creating an interval, that should be used by users. We could even (I believe) not export the `Interval` object itself!

Any comments, @lbenet?

**Comment by dpsanders** [comment]
(Closed accidentally.)

**Comment by lbenet** [comment]
I understand the idea, but I'm not so sure about it; I'm simply thinking about the "validated" part of all that. 

What about implementing an `UnsafeInterval` type (or whatever name you want) which does what you want (and is not exported), and the relevant methods to convert it to an `Interval`, which involves checking the correctness of the interval?

**Comment by dpsanders** [comment]
Given a valid interval, all the functions in the library will return a valid interval.
(If they didn't, then the current test suite would fail.)

So the problem is only constructing valid intervals to start with, which is what the `interval` function will check for.

Using an `UnsafeInterval` type will simply require rewriting every function in the library to use it ;)

**Comment by dpsanders** [comment]
Although it's possible that it would be useful to make a `SafeInterval` type that does the

**Comment by lbenet** [comment]
Whatever (`SafeInterval` or `UnsafeInterval`) I think this is more convenient than the function `interval`, since we would be dispatching on them. 

The question is how to enforce the user to use the `SafeInterval`? I think we should do it by only exporting the `SafeInterval` version (currently `Interval`) and constructing a fast conversion from `UnsafeInterval` to `SafeInterval`. Yet, I'm not sure how to avoid the checks in `SafeInterval`...

**Comment by dpsanders** [comment]
I have implemented a simpler solution in the `simplify_constructor` branch: there is a global variable `validity_check` defined at the start of `intervals.jl`. If it is true, then the validity check is compiled into the constructor; if not, then the validity check is omitted.

Currently you have to manually go and change it in that file, and then do `using IntervalArithmetic`,  and validity checks will be enabled.

If validity checks are disabled, then the `interval` function validates the input and creates the interval.

**Comment by dpsanders** [comment]
Not sure what else there is to do here.

**Comment by lbenet** [comment]
Same as for #36...

**Comment by dpsanders** [comment]
This has been done: the `Interval` constructor does no checks; checks are done by using `interval`.
