### ISSUE TITLE
a..b should have different modes

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#90]
We should (maybe?) be able to change the precision of `a..b`.
Currently it does `Interval(prevfloat(a), nextfloat(b))` for performance, but we lose a modicum of precision.

**Comment by lucaferranti** [comment]
currently `a..b` uses rationalize, `interval` does validity check but no "rounding black magic". Parsing from strings gives the exact tight result (at least after I fixed the parser in 1.0-dev)
