### ISSUE TITLE
Segfault for printing of intervals in 0.7, with possible fix

### ISSUE THREAD

**Issue by cyberbryce** [JuliaIntervals/IntervalArithmetic.jl#93]
While `IntervalArithmetic` successfully precompiles on Julia 0.7/1.0 as of yesterday afternoon  (Julia 0.7.0-DEV.3222), any attempt to print an `Interval` object currently leads to a segfault, at least on a recent Intel/Darwin setup.

I think I've the issue to the utility function "round_string" which is used to round for pretty printing. Since latest commit of "IntervalArithmetic.jl/src/display.jl" (https://github.com/JuliaIntervals/IntervalArithmetic.jl/commit/96e9d8083d50bbc6c3ee349a690c48fcbab97226) the definition is 

```julia
# round to given number of signficant digits
# basic structure taken from string(x::BigFloat) in base/mpfr.jl
function round_string(x::BigFloat, digits::Int, r::RoundingMode)

    lng = digits + Int32(8)
    buf = Array{UInt8}(lng + 1)

    lng = ccall((:mpfr_snprintf,:libmpfr), Int32,
    (Ptr{UInt8}, Culong,  Ptr{UInt8}, Int32, Ptr{BigFloat}...),
    buf, lng + 1, "%.$(digits)R*g", Base.MPFR.to_mpfr(r), &x)

    repr = unsafe_string(pointer(buf))

    repr = replace(repr, "nan", "NaN")

    return repr
end
```

The syntax for passing references to C functions, as is used here to operate directly on a `BigFloat` object using the MPFR C library function `snprintf`, changes in 0.7/1.0. While the old syntax ought to still work, in `round_string` changing the syntax as follows appears to avoid the segfault:

```julia
function round_string(x::BigFloat, digits::Int, r::RoundingMode)

    lng = digits + Int32(8)
    buf = Array{UInt8}(lng + 1)

    lng = ccall((:mpfr_snprintf,:libmpfr), Int32,
    (Ptr{UInt8}, Culong,  Ptr{UInt8}, Int32, Ref{BigFloat}...),
    buf, lng + 1, "%.$(digits)R*g", Base.MPFR.to_mpfr(r), x)

    repr = unsafe_string(pointer(buf))

    repr = replace(repr, "nan", "NaN")

    return repr
end
```

**Comment by dpsanders** [comment]
Thanks very much for the bug report and fix!  Apologies for the delay in looking at this.

Would you like to make a Pull Request to fix this?

**Comment by dpsanders** [comment]
There is a branch fix_ccall with this change. It is currently on top of v0.11.
Thanks!

**Comment by dpsanders** [comment]
Thanks @cyberbryce!
