### ISSUE TITLE
Add parse(Interval, s) for a string s

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#95]
Add 
- [ ] `parse(Interval, "1e-400")`
- [ ] `convert(Interval, "1e-400")`

This is part of the string input and output required by the standard. We should check the details.

**Comment by dpsanders** [comment]
Currently we have `parse(Interval{Float64}, s)`.
To define `parse(Interval, s)` we would have to fix a default precision interval to parse to.

**Comment by lbenet** [comment]
> To define parse(Interval, s) we would have to fix a default precision interval to parse to.

`Float64` would be my naive choice, which agrees with `@interval` (unless used with `BigFloat`s).

**Comment by dpsanders** [comment]
The other option is to use the global precision type in `parameters.precision_type`.
But we probably want to move away from using global parameters like that.
